### PR TITLE
correcting setup.sh help command

### PR DESCRIPTION
**Pull request by gizmocuz**
to display the help from setup.sh we need to use '-help ' instead of 'help'

# Description

Fixes #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by georglauterbach** [comment]
> to display the help from setup.sh we need to use '-help ' instead of 'help'

I am not sure how you come to this conclusion. Could you elaborate? Using `./setup.sh help` works flawlessly for me.. while `./setup.sh -help` produces:

``` CONSOLE
$ ./setup.sh -help
Invalid option: '-h'
Use './setup.sh help' to get a complete overview.
```

Sorry, but I think this is just plain wrong.

**Comment by gizmocuz** [comment]
I followed the steps from the readme.md and here is my output (from a debian system)

You could be right here, but 'help' is not helping either:

```
root@inferno:/opt/mailserver# ./setup.sh help
[dumb-init] setup: No such file or directory
```
and now with -help

```
root@inferno:/opt/mailserver# ./setup.sh -help
Invalid option: '-h'
Use './setup.sh help' to get a complete overview.

OPTIONS
    Config path, container or image adjustments
        -i IMAGE_NAME
            Provides the name of the 'docker-mailserver' image. The default value is
            'docker.io/mailserver/docker-mailserver:latest'

        -c CONTAINER_NAME
            Provides the name of the running container.

        -p PATH
            Provides the local path of the config folder to the temporary container instance.
            Does not work if an existing a 'docker-mailserver' container is already running.

    SELinux
        -z
            Allows container access to the bind mount content that is shared among
            multiple containers on a SELinux-enabled host.

        -Z
            Allows container access to the bind mount content that is private and
            unshared with other containers on a SELinux-enabled host.

    Podman
        -R
            Accept running in Podman rootless mode. Ignored when using Docker / Docker Compose.
```

Paying a closer look at the output says it does not know -help ... it shows 'some help' better than none 😁

**Comment by georglauterbach** [comment]
> I followed the steps from the readme.md and here is my output (from a debian system)
> 
> You could be right here, but 'help' is not helping either:
> 
> ```
> root@inferno:/opt/mailserver# ./setup.sh help
> 
> [dumb-init] setup: No such file or directory
> ```

Are you using a special version of the image? Your output suggests the script `setup` is non-existent in your image, which would mean the image is from before v10.0.0 I think. Are you using the latest `setup.sh` version? **Remove all images of `docker-mailserver` on your host** and please try again.

**Comment by gizmocuz** [comment]
```
rm -Rf /opt/mailserver/
mkdir /opt/mailserver
cd /opt/mailserver
```

```
DMS_GITHUB_URL='https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master'
wget "${DMS_GITHUB_URL}/setup.sh"
chmod a+x ./setup.sh
```

```
root@inferno:/opt/mailserver# ./setup.sh help
[dumb-init] setup: No such file or directory
```

Sorry same as above

**Comment by georglauterbach** [comment]
I meant: remove the currently used images, i.e. `docker image rm <IMAGE>`.

**Comment by gizmocuz** [comment]
That did the trick! Sorry didn't know this could be of influence!
Working like a charm, again sorry to waisted your time!

**Pull request closed without merging**
