### PR TITLE
v10.1.0 release

### PR DESCRIPTION
**Pull request by wernerfred**
# Description

This PR marks the feature freeze phase for `v10.1.0` release. The current `:edge` image will be tested for roughly one week and if no bugs get reported `v10.1.0` will be released. During this testing period no new PRs will be merged.

**If you want to support us give the latest `:edge` image a try and report any issues you might (hopefully not) encounter back to this PR.**

## Type of change

- [x] Release

## Checklist:

- [x] Update `CHANGELOG.md`
- [x] Update references in `README.md`
- [x] Update version in `VERSION`
- [x] ...

### CODE REVIEW

**Comment by wernerfred** [comment]
I will create the 10.1.0 release draft in the next days.

**Comment by georglauterbach** [comment]
I'm going to be on holiday the next days. Therefore, I can approve this now in case I don't get to later :D

**Review by georglauterbach — DISMISSED** [review]

**Comment by georglauterbach** [comment]
#2109 should be merged first though @casperklein :)

**Comment by wernerfred** [comment]
Added the release draft (https://github.com/docker-mailserver/docker-mailserver/releases/tag/untagged-b074182522b79693a7c4) 
Has someone encountered any issues so far @docker-mailserver/maintainers ?

**Comment by casperklein** [comment]
No issues in my setup. :+1:

**Review by georglauterbach — DISMISSED** [review]

**Comment by georglauterbach** [comment]
@wernerfred I think this can be merged. Can you merge this and release `v10.1.0`?

**Comment by wernerfred** [comment]
Will merge and release later today. Need to update the changelog and few other notes first and carefully examine my logs again for any abnormalities

**Review by georglauterbach — APPROVED** [review]

**Comment by georglauterbach** [comment]
LGTM 👍🏼

**Comment by wernerfred** [comment]
I will publish the release once the CI passed

**Comment by wernerfred** [comment]
Workflow might be delayed some time. Github Actions Service is degraded right now: https://www.githubstatus.com/

**Review by williamdes — COMMENTED** [review]
LGTM too

Sorry if I am not spending as much time as I would like on this amazing project
I have zero issues in production with it and my users are happy
Thank you for maintaining this project !

Hope to help, feel free to assign me as reviewer on PRs when you think it is needed

By the way I review ALL of the diff between each release from the previous one I allowed into production, did not detect anything, very good work 🚢

**Pull request merged**
