### PR TITLE
Rename function and adjust comment

### PR DESCRIPTION
**Pull request by casperklein**
# Description

After a second view on the function, I think this makes more sense.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by polarathene — COMMENTED** [review]
Probably not necessary due to the rename of the function (good change btw!), although I wasn't immediately sure what the actual output returned was and verified it's `0` or `1`, previously I thought it was returning the original string or an empty string (if it was detected as a comment) :sweat_smile:

**Comment by casperklein** [comment]
Functions cannot return strings. They return the exit status of the last command. In case of grep, the man page states 3 options:

> Normally the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.

If you want a string to be returned, you can use something like:

```sh
foo() {
        echo "some string"
}
output=$(foo)
echo $output
```

The comment adjustment is correct, as the function does not actually remove anything. Or did you mean to remove the comment entirely? I would keep it.

**Comment by polarathene** [comment]
> Or did you mean to remove the comment entirely? I would keep it.

Oh no the current changes are all great. I was meaning that I wasn't sure what to expect the return value to be, but assumed it was something truthy/falsey, tried it and noted it was `0` or `1` which made sense :sweat_smile: 

I wasn't aware about that with grep or functions, but probably because in the past I've used echo with functions that I called via subshells :)

I think it's fine as is, even for those less confident with bash/scripts the new name is clear it should be a true/false type of value, as well as the usage in an if statement. `git blame` for the curious is probably sufficient for the added clarification you've covered here :+1:

**Review by polarathene — APPROVED** [review]
LGTM! (_sorry, my previous review was meant to be an approval_ :sweat_smile: )

**Review by georglauterbach — APPROVED** [review]

**Review by wernerfred — APPROVED** [review]

**Comment by georglauterbach** [comment]
Just FYI: Nothing will break, but this was marked as `meta/feature-freeze` - it should not have been merged :) But no worries there, just for the next time.

**Comment by casperklein** [comment]
> this was marked as meta/feature-freeze

Sorry, I overlooked that. I added the v10.3.0 milestone and got approval. That's why I thought it was okay to merge.

**Pull request merged**
