### PR TITLE
Adjusted documentation for service name and Traefik certificate issuance

### PR DESCRIPTION
**Pull request by aendeavor**
# Description

- changed container name from `mail` to `mailserver` to streamline docs
- some braces around variables in Bash scripts were added
- changed Traefik's certificate section
  - removed docs for Traefik v1 - we want everyone to use Traefik v2 from `9.2.0`
  - **the wildcard certificate issue** in #1915 was addressed
  - proper indentation was added

I have drafted a prerelease for `v9.2.0`. Have a look :)

### TODO

1. Make sure the adjustments to `SSL_DOMAIN` are correct (by solving #1915)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the documentation)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
> I have drafted a prerelease for v9.2.0. Have a look :)

fyi: I've edited two fail2ban related things.

This release contains "breaking changes". Even if I can't imagine, what could break, the possibility is given. Per definition, breaking changes should only be done in major updates.

@docker-mailserver/maintainers Should we aim 9.2 or 10.0 in that case?

**Comment by aendeavor** [comment]
> > I have drafted a prerelease for v9.2.0. Have a look :)
> 
> 
> 
> fyi: I've edited two fail2ban related things.
> 
> 
> 
> This release contains "breaking changes". Even if I can't imagine, what could break, the possibility is given. Per definition, breaking changes should only be done in major updates.
> 
> 
> 
> @docker-mailserver/maintainers Should we aim 9.2 or 10.0 in that case?

You may be right, it was written out of caution. I'd pledge against `10.0.0`, since these are many, but rather small changes. But I'd leave this up to a vote. Again, this is only a pre-release so we can have a look and decide.

**Review by wernerfred — APPROVED** [review]
LGTM 👍🏻

**Comment by wernerfred** [comment]
> You may be right, it was written out of caution. I'd pledge against `10.0.0`, since these are many, but rather small changes. But I'd leave this up to a vote. Again, this is only a pre-release so we can have a look and decide.

Basically this have to be `v10.0.0` but this (rather fast) rising numbers are the cause many other software projects are shifting the semver and use: `core.major.minor`. As we commited to use Semver we should stick with it and use `10.0.0`. If we have trouble in the future with this numbers we could think of resetting the counter but I would keep it transparent to users that (even if the possibility is low) the next update could break their setup.

**Review by casperklein — APPROVED** [review]

**Comment by aendeavor** [comment]
Alright. When #1901 is merged, we will release `v10.0.0` :)

**Pull request merged**
