### PR TITLE
fix: `supervisor-app.conf` - Correct the log location for `postgrey`

### PR DESCRIPTION
**Pull request by polarathene**
# Description

Looks like this should have been like every other service and reference a log file(s) based on program name in the supervisor log directory.

- The prior location [`/var/log/mail/mail.log` has a symlink from `/var/log/mail.log`](https://github.com/docker-mailserver/docker-mailserver/pull/3640/files#r1393325507) created in the `Dockerfile`.
- [`/var/log/mail/mail.log` is created at container startup](https://github.com/docker-mailserver/docker-mailserver/blob/3adb53eb1213c8848fdf44cf2343392c1817d094/target/scripts/start-mailserver.sh#L178-L179) and tailed as [part of the `mailserver` supervisord service](https://github.com/docker-mailserver/docker-mailserver/blob/3adb53eb1213c8848fdf44cf2343392c1817d094/target/supervisor/conf.d/supervisor-app.conf#L12-L16).

---

This should fix a [recently reported failure](https://github.com/docker-mailserver/docker-mailserver/pull/3480#issuecomment-1868620578) from running the new `make run-local-instance` dev command:

```
Error: The directory named as part of the path /var/log/mail/mail.log does not exist in section 'program:postgrey' (file: '/etc/supervisor/conf.d/supervisor-app.conf')
For help, use /usr/bin/supervisord -h
make: *** [Makefile:37: run-local-instance] Error 2
```

**NOTE:** I haven't verified this yet, just preparing the PR in anticipation that it addresses the issue.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

**Comment by polarathene** [comment]
Test failures due to log location changing:

```
not ok 60 [Postgrey] (enabled) should initially reject (greylist) mail from 'user@external.tld' in 11003ms
# (from function `_run_until_success_or_timeout' in file test/helper/common.bash, line 222,
#  from function `_should_have_log_entry' in file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 124,
#  in test file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 58)
#   `'action=greylist' \' failed

# Timed out on command: _exec_in_container grep action=greylist, reason=new, /var/log/mail/mail.log
not ok 61 [Postgrey] (enabled) should accept mail from 'user@external.tld' after POSTGREY_DELAY duration in 13815ms
# (from function `_run_until_success_or_timeout' in file test/helper/common.bash, line 222,
#  from function `_should_have_log_entry' in file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 124,
#  in test file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 76)
#   `'action=pass' \' failed

# Timed out on command: _exec_in_container grep action=pass, reason=triplet found, /var/log/mail/mail.log
not ok 62 [Postgrey] (enabled) should whitelist sender 'user@whitelist.tld' in 10940ms
# (from function `_run_until_success_or_timeout' in file test/helper/common.bash, line 222,
#  from function `_should_have_log_entry' in file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 124,
#  in test file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 93)
#   `'action=pass' \' failed

# Timed out on command: _exec_in_container grep action=pass, reason=client whitelist, /var/log/mail/mail.log
not ok 63 [Postgrey] (enabled) should whitelist recipient 'user2@otherdomain.tld' in 10944ms
# (from function `_run_until_success_or_timeout' in file test/helper/common.bash, line 222,
#  from function `_should_have_log_entry' in file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 124,
#  in test file test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, line 102)
#   `'action=pass' \' failed
# Timed out on command: _exec_in_container grep action=pass, reason=recipient whitelist, /var/log/mail/mail.log
```

All due to those test cases calling this common method to get logs:

https://github.com/docker-mailserver/docker-mailserver/blob/3adb53eb1213c8848fdf44cf2343392c1817d094/test/tests/parallel/set1/spam_virus/postgrey_enabled.bats#L118-L131

Looks like that should be fine with updating the location. The Postgrey tests additional refer to the main logs in one other location, which I think is for Postfix logs:

https://github.com/docker-mailserver/docker-mailserver/blob/3adb53eb1213c8848fdf44cf2343392c1817d094/test/tests/parallel/set1/spam_virus/postgrey_enabled.bats#L62-L64

**Review by georglauterbach — APPROVED** [review]

**Comment by thechubbypanda** [comment]
Just testing this branch, getting the same error again but with rspamd:
```
Error: The directory named as part of the path /var/log/mail/rspamd.log does not exist in section 'program:rspamd' (file: '/etc/supervisor/conf.d/supervisor-app.conf')
```

**Comment by thechubbypanda** [comment]
Ok nevermind... It appears some remaining `docker-data` or something was messing things up. I cleaned the lot and now it appears to be working. I'm just so confused as to why it's now working as I even re-cloned the repo...

**Comment by polarathene** [comment]
> Ok nevermind... It appears some remaining `docker-data` or something was messing things up.

That does seem odd, but glad it's not likely a bug in v13.1 😅 

I guess we can merge this as an improvement still. Shall we delay it to v14 then @georglauterbach ? (_otherwise feel free to merge_)

---

If you'd like to share some information about your environment here, it might help troubleshoot if we get any similar reports.

I know I've recently had some issues with WSL2 with Docker (_not possible to use host networking mode, at least not with binding ports within WSL distro, whilst bridge networks aren't accessible on the Windows host, only localhost via port publishing...which would require split DNS for my CoreDNS server to return `127.0.0.1` to windows and container IPs within containers_).

**Comment by georglauterbach** [comment]
I think it's best to delay until v14.0.0.

**Review by casperklein — APPROVED** [review]

**Pull request merged**
