### PR TITLE
Remove stable branch from CI and build edge on schedule

### PR DESCRIPTION
**Pull request by casperklein**
# Description

1. The stable branch has been removed from the CI.
2. The scheduled build has been adjusted: stable --> edge.

After this PR is merged, the stable branch can be deleted.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
Any suggestions?

**Comment by aendeavor** [comment]
I like it, LGTM, but I would wait for other maintainers to give their opninion before merging this (of course :D) 👍

**Review by aendeavor — APPROVED** [review]

**Review by wernerfred — APPROVED** [review]
LGTM

**Review by polarathene — APPROVED** [review]

**Comment by aendeavor** [comment]
I will keep the `:stable` tag on DockerHub for a few weeks to not throw over someone who uses this tag ATM. I may give a deprecation notice in the README on DockerHub.

**Pull request merged**
