### PR TITLE
issue with existing alias which doesn't exist

### PR DESCRIPTION
**Pull request by bibiak1**
# Description

Issue with adding new recipient to existing alias
If new recipient exists as alias in db then setup is throwing error.

Fixes part of script checks only the relevant alias and compares recipients for it.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by georglauterbach** [comment]
> If new recipient exists as alias in db then setup is throwing error.

That behavior seems reasonable to me. Why would you change that?

**Review by georglauterbach — CHANGES_REQUESTED** [review]
Blocking this until discussion about actual issue is resolved.

**Comment by bibiak1** [comment]
https://github.com/docker-mailserver/docker-mailserver/issues/3262

**Comment by bibiak1** [comment]
It's now an issue. It is a rmaik forwarding feature. How to forward email if you blocked alias for email account?

**Comment by georglauterbach** [comment]
> How to forward email if you blocked alias for email account?

We did not block alias for email accounts, we blocked aliases **that are equal to** accounts.

> It's now an issue. It is a email forwarding feature.

Not quite; you're not actually forwarding / relaying an email, because this would imply that either DMS is the new sender (forwarding) or DMS is not the addressee but an intermediate MTA (relaying). You somehow want Gmail to act on DMS. @polarathene has proposed a solution in <https://github.com/docker-mailserver/docker-mailserver/issues/3262#issuecomment-1509366419> for the issue you raised.

**Comment by bibiak1** [comment]
> Not quite; you're not actually forwarding / relaying an email, because this would imply that either DMS is the new sender (forwarding) or DMS is not the addressee but an intermediate MTA (relaying). You somehow want Gmail to act on DMS. @polarathene has proposed a solution in [#3262 (comment)](https://github.com/docker-mailserver/docker-mailserver/issues/3262#issuecomment-1509366419) for the issue you raised.

It was not my concern that there's an alias for account. I raised other concern

**Pull request closed without merging**
