### PR TITLE
update: Dovecot FTS Xapian from 1.5.5 to 1.7.12

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

I wanted to get this into v14.0.0 because I want to start using Xapian myself.

**Auto-merge is enabled for this PR!**

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary, I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

**Review by casperklein — APPROVED** [review]

**Comment by casperklein** [comment]
BTW: Fail2ban got an update, which fixes some [postfix issues](https://github.com/fail2ban/fail2ban/blob/1.1.0/ChangeLog). This should also go into v14. What's your take @georglauterbach and @polarathene

**Comment by georglauterbach** [comment]
> BTW: Fail2ban got an update, which fixes some [postfix issues](https://github.com/fail2ban/fail2ban/blob/1.1.0/ChangeLog). This should also go into v14. What's your take @georglauterbach and @polarathene 

Agreed; I will provide a PR.

**Comment by casperklein** [comment]
It is. We used the provided [.deb](https://github.com/fail2ban/fail2ban/releases/download/1.1.0/fail2ban_1.1.0-1.upstream1_all.deb) file in the past.

**Comment by georglauterbach** [comment]
So you're proposing "reverting" to the old approach, using the deb file? I mean, I do not particularly like that, but if the upgrade is worthwhile.

Just one question: will the update not land on Debian Bookworm in the near future?

**Comment by casperklein** [comment]
> So you're proposing "reverting" to the old approach, using the deb file?

Yes. I was just looking for the [commit ](https://github.com/docker-mailserver/docker-mailserver/commit/00018e7e2b226fafb3a5ab50db078885ca6c8ddc#diff-95c6b88025d3f0c1a18f85c2c05a14faa73ff59b57f6e938df5113221c8018f1) that removed it to update my post.

In the past, there were large gaps between the version in the Debian repo and the latest provided by Fail2ban.

**Comment by polarathene** [comment]
> What's your take @georglauterbach and @polarathene

Debian is disappointing with package lag, go ahead 👍 

Personally I'd rather we migrate to something like Fedora in future, but I think that's lacking rspamd 🤷‍♂️ Maybe going back to Ubuntu base is a reasonable compromise? Still `.deb` / `apt` based but should have newer packages.

I'm not suggesting we switch any time soon though, there's probably some implicit environment changes like `/etc/services` and `/etc/mailname` (_or one of these related to the hostname_) that can differ, none of us want to mess around with that 😂

**Pull request merged**
