### PR TITLE
chore(ci): Linting Improved

### LINKED ISSUE #1997: Local lint results are different from CI
I'm running the linting locally and seeing different results from the CI that gets run on the PR (which shows 0 issues):

```
root@b543b5b29108:/home/ubuntu/docker-mailserver# make eclint

––– EDITORCONFIG LINTER
  – type    = INFO
  – message = linter version: 2.3.1

Makefile:
        Wrong line endings or new final newline
target/docker-configomat/test/test_helper/bats-support/src/output.bash:
        13: Trailing whitespace
test/bats/.devcontainer/Dockerfile:
        Line too long (103 instead of 80)
test/bats/.travis.yml:
        24: Wrong amount of left-padding spaces(want multiple of 2)
        25: Wrong amount of left-padding spaces(want multiple of 2)
        26: Wrong amount of left-padding spaces(want multiple of 2)
        27: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (88 instead of 80)
test/bats/contrib/release.sh:
        Line too long (101 instead of 80)
        Line too long (86 instead of 80)
        Line too long (85 instead of 80)
        Line too long (98 instead of 80)
        Line too long (109 instead of 80)
test/bats/contrib/rpm/bats.spec:
        Line too long (81 instead of 80)
        Line too long (87 instead of 80)
        Line too long (103 instead of 80)
        Line too long (96 instead of 80)
test/bats/contrib/semver:
        32: Wrong amount of left-padding spaces(want multiple of 2)
        33: Wrong amount of left-padding spaces(want multiple of 2)
        34: Wrong amount of left-padding spaces(want multiple of 2)
        36: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (86 instead of 80)
        Line too long (81 instead of 80)
        Line too long (82 instead of 80)
        40: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (89 instead of 80)
        Line too long (85 instead of 80)
        55: Wrong amount of left-padding spaces(want multiple of 2)
        56: Wrong amount of left-padding spaces(want multiple of 2)
        57: Wrong amount of left-padding spaces(want multiple of 2)
        58: Wrong amount of left-padding spaces(want multiple of 2)
        61: Wrong amount of left-padding spaces(want multiple of 2)
        62: Wrong amount of left-padding spaces(want multiple of 2)
        65: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (122 instead of 80)
        Line too long (82 instead of 80)
        149: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (98 instead of 80)
        153: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (101 instead of 80)
        Line too long (92 instead of 80)
        Line too long (86 instead of 80)
        198: Wrong amount of left-padding spaces(want multiple of 2)
        202: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (81 instead of 80)
        Line too long (88 instead of 80)
test/bats/docs/CODEOWNERS:
        Line too long (81 instead of 80)
test/bats/install.sh:
        Line too long (84 instead of 80)
test/bats/lib/bats-core/preprocessing.bash:
        4: Wrong amount of left-padding spaces(want multiple of 2)
        6: Wrong amount of left-padding spaces(want multiple of 2)
        15: Wrong amount of left-padding spaces(want multiple of 2)
        16: Wrong amount of left-padding spaces(want multiple of 2)
        17: Wrong amount of left-padding spaces(want multiple of 2)
        18: Wrong amount of left-padding spaces(want multiple of 2)
        22: Wrong amount of left-padding spaces(want multiple of 2)
        26: Wrong amount of left-padding spaces(want multiple of 2)
        27: Wrong amount of left-padding spaces(want multiple of 2)
        28: Wrong amount of left-padding spaces(want multiple of 2)
        29: Wrong amount of left-padding spaces(want multiple of 2)
        30: Wrong amount of left-padding spaces(want multiple of 2)
        31: Wrong amount of left-padding spaces(want multiple of 2)
test/bats/lib/bats-core/test_functions.bash:
        Line too long (81 instead of 80)
        Line too long (116 instead of 80)
test/bats/lib/bats-core/tracing.bash:
        4: Wrong amount of left-padding spaces(want multiple of 2)
        5: Wrong amount of left-padding spaces(want multiple of 2)
        6: Wrong amount of left-padding spaces(want multiple of 2)
        8: Wrong amount of left-padding spaces(want multiple of 2)
        10: Wrong amount of left-padding spaces(want multiple of 2)
        11: Wrong amount of left-padding spaces(want multiple of 2)
        12: Wrong amount of left-padding spaces(want multiple of 2)
        13: Wrong amount of left-padding spaces(want multiple of 2)
        14: Wrong amount of left-padding spaces(want multiple of 2)
        15: Wrong amount of left-padding spaces(want multiple of 2)
        16: Wrong amount of left-padding spaces(want multiple of 2)
        17: Wrong amount of left-padding spaces(want multiple of 2)
        18: Wrong amount of left-padding spaces(want multiple of 2)
        19: Wrong amount of left-padding spaces(want multiple of 2)
        20: Wrong amount of left-padding spaces(want multiple of 2)
        21: Wrong amount of left-padding spaces(want multiple of 2)
        22: Wrong amount of left-padding spaces(want multiple of 2)
        23: Wrong amount of left-padding spaces(want multiple of 2)
        27: Wrong amount of left-padding spaces(want multiple of 2)
        28: Wrong amount of left-padding spaces(want multiple of 2)
        29: Wrong amount of left-padding spaces(want multiple of 2)
        30: Wrong amount of left-padding spaces(want multiple of 2)
        31: Wrong amount of left-padding spaces(want multiple of 2)
        33: Wrong amount of left-padding spaces(want multiple of 2)
        34: Wrong amount of left-padding spaces(want multiple of 2)
        35: Wrong amount of left-padding spaces(want multiple of 2)
        36: Wrong amount of left-padding spaces(want multiple of 2)
        38: Wrong amount of left-padding spaces(want multiple of 2)
        39: Wrong amount of left-padding spaces(want multiple of 2)
        40: Wrong amount of left-padding spaces(want multiple of 2)
        41: Wrong amount of left-padding spaces(want multiple of 2)
        42: Wrong amount of left-padding spaces(want multiple of 2)
        44: Wrong amount of left-padding spaces(want multiple of 2)
        45: Wrong amount of left-padding spaces(want multiple of 2)
        46: Wrong amount of left-padding spaces(want multiple of 2)
        47: Wrong amount of left-padding spaces(want multiple of 2)
        48: Wrong amount of left-padding spaces(want multiple of 2)
        50: Wrong amount of left-padding spaces(want multiple of 2)
        51: Wrong amount of left-padding spaces(want multiple of 2)
        52: Wrong amount of left-padding spaces(want multiple of 2)
        53: Wrong amount of left-padding spaces(want multiple of 2)
        54: Wrong amount of left-padding spaces(want multiple of 2)
        56: Wrong amount of left-padding spaces(want multiple of 2)
        57: Wrong amount of left-padding spaces(want multiple of 2)
        61: Wrong amount of left-padding spaces(want multiple of 2)
        62: Wrong amount of left-padding spaces(want multiple of 2)
        63: Wrong amount of left-padding spaces(want multiple of 2)
        64: Wrong amount of left-padding spaces(want multiple of 2)
        65: Wrong amount of left-padding spaces(want multiple of 2)
        67: Wrong amount of left-padding spaces(want multiple of 2)
        68: Wrong amount of left-padding spaces(want multiple of 2)
        69: Wrong amount of left-padding spaces(want multiple of 2)
        70: Wrong amount of left-padding spaces(want multiple of 2)
        71: Wrong amount of left-padding spaces(want multiple of 2)
        73: Wrong amount of left-padding spaces(want multiple of 2)
        74: Wrong amount of left-padding spaces(want multiple of 2)
        75: Wrong amount of left-padding spaces(want multiple of 2)
        76: Wrong amount of left-padding spaces(want multiple of 2)
        77: Wrong amount of left-padding spaces(want multiple of 2)
        81: Wrong amount of left-padding spaces(want multiple of 2)
        85: Wrong amount of left-padding spaces(want multiple of 2)
        86: Wrong amount of left-padding spaces(want multiple of 2)
        90: Wrong amount of left-padding spaces(want multiple of 2)
        91: Wrong amount of left-padding spaces(want multiple of 2)
        93: Wrong amount of left-padding spaces(want multiple of 2)
        94: Wrong amount of left-padding spaces(want multiple of 2)
        95: Wrong amount of left-padding spaces(want multiple of 2)
        96: Wrong amount of left-padding spaces(want multiple of 2)
        100: Wrong amount of left-padding spaces(want multiple of 2)
        101: Wrong amount of left-padding spaces(want multiple of 2)
        103: Wrong amount of left-padding spaces(want multiple of 2)
        104: Wrong amount of left-padding spaces(want multiple of 2)
        105: Wrong amount of left-padding spaces(want multiple of 2)
        106: Wrong amount of left-padding spaces(want multiple of 2)
        107: Wrong amount of left-padding spaces(want multiple of 2)
        108: Wrong amount of left-padding spaces(want multiple of 2)
        112: Wrong amount of left-padding spaces(want multiple of 2)
        113: Wrong amount of left-padding spaces(want multiple of 2)
        117: Wrong amount of left-padding spaces(want multiple of 2)
        121: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (89 instead of 80)
        122: Wrong amount of left-padding spaces(want multiple of 2)
        123: Wrong amount of left-padding spaces(want multiple of 2)
        124: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (81 instead of 80)
        125: Wrong amount of left-padding spaces(want multiple of 2)
        126: Wrong amount of left-padding spaces(want multiple of 2)
        127: Wrong amount of left-padding spaces(want multiple of 2)
        128: Wrong amount of left-padding spaces(want multiple of 2)
        129: Wrong amount of left-padding spaces(want multiple of 2)
        130: Wrong amount of left-padding spaces(want multiple of 2)
        145: Wrong amount of left-padding spaces(want multiple of 2)
        146: Wrong amount of left-padding spaces(want multiple of 2)
        147: Wrong amount of left-padding spaces(want multiple of 2)
        148: Wrong amount of left-padding spaces(want multiple of 2)
        149: Wrong amount of left-padding spaces(want multiple of 2)
        150: Wrong amount of left-padding spaces(want multiple of 2)
        151: Wrong amount of left-padding spaces(want multiple of 2)
        152: Wrong amount of left-padding spaces(want multiple of 2)
        153: Wrong amount of left-padding spaces(want multiple of 2)
test/bats/lib/bats-core/validator.bash:
        Wrong line endings or new final newline
        Line too long (129 instead of 80)
test/bats/libexec/bats-core/bats:
        22: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (93 instead of 80)
        Line too long (82 instead of 80)
        Line too long (89 instead of 80)
        Line too long (133 instead of 80)
test/bats/libexec/bats-core/bats-exec-file:
        Line too long (93 instead of 80)
        Line too long (86 instead of 80)
        Line too long (138 instead of 80)
        Line too long (84 instead of 80)
        Line too long (204 instead of 80)
        Line too long (104 instead of 80)
        Line too long (90 instead of 80)
test/bats/libexec/bats-core/bats-exec-suite:
        Line too long (153 instead of 80)
test/bats/libexec/bats-core/bats-exec-test:
        Line too long (124 instead of 80)
        Line too long (95 instead of 80)
        Line too long (91 instead of 80)
test/bats/libexec/bats-core/bats-format-junit:
        Line too long (125 instead of 80)
        Line too long (114 instead of 80)
        Line too long (110 instead of 80)
        Line too long (85 instead of 80)
test/bats/libexec/bats-core/bats-format-pretty:
        Line too long (118 instead of 80)
test/bats/libexec/bats-core/bats-preprocess:
        Line too long (89 instead of 80)
test/bats/man/bats.1:
        Line too long (121 instead of 80)
        Line too long (142 instead of 80)
        Line too long (150 instead of 80)
        Line too long (282 instead of 80)
        Line too long (291 instead of 80)
        Line too long (287 instead of 80)
        Line too long (91 instead of 80)
        Line too long (161 instead of 80)
        67: Wrong amount of left-padding spaces(want multiple of 2)
        68: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (311 instead of 80)
        Line too long (124 instead of 80)
test/bats/man/bats.1.ronn:
        9: Wrong amount of left-padding spaces(want multiple of 2)
        Line too long (86 instead of 80)
        86: Wrong amount of left-padding spaces(want multiple of 2)
        87: Wrong amount of left-padding spaces(want multiple of 2)
test/bats/man/bats.7:
        Line too long (150 instead of 80)
        Line too long (223 instead of 80)
        Line too long (338 instead of 80)
        Line too long (166 instead of 80)
        Line too long (192 instead of 80)
        Line too long (235 instead of 80)
        Line too long (266 instead of 80)
        Line too long (158 instead of 80)
        Line too long (94 instead of 80)
        Line too long (207 instead of 80)
        Line too long (437 instead of 80)
        Line too long (82 instead of 80)
        Line too long (84 instead of 80)
        Line too long (91 instead of 80)
        Line too long (93 instead of 80)
test/bats/package.json:
        No final newline expected
test/bats/test/test_helper.bash:
        Line too long (95 instead of 80)
test/test_helper/bats-support/src/output.bash:
        13: Trailing whitespace

221 errors found

––– EDITORCONFIG LINTER
  – type    = FAILURE
  – message = 'errors encountered'

make: *** [Makefile:67: eclint] Error 1
```

I looked at the github actions for the linting and I'm not seeing the difference or reason for this. What am I missing?

### PR DESCRIPTION
**Pull request by aendeavor**
# Description

Improves and updates the linting procedures.

1. Bumped linter versions to their latest release as of today.
2. Streamlined `test/linting/lint.sh`
3. Added new configuration file for ECLint
4. Had to update `start-mailserver` and `setup-stack.sh` as ShellCheck was complaining with v0.7.2. So I revised `SPAMASSASIN_SPAM_TO_INBOX_SET` for the better and removed the ugly sub-shell usage which was totally unnecessary.

Fixes #1997

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

---

PS: I got the PR marked with #2000 🎉

### CODE REVIEW

**Comment by aendeavor** [comment]
Note: I stopped all but the latest CI runs on purpose :)

**Comment by NorseGaud** [comment]
Linking the PRs for a paper-trail: https://github.com/docker-mailserver/docker-mailserver/pull/2001 includes all of these changes too

**Review by polarathene — APPROVED** [review]

**Comment by wernerfred** [comment]
@all-contributors add @georglauterbach for maintenance,code,question,review

**Comment by wernerfred** [comment]
@all-contributors add @georglauterbach for maintenance

**Pull request merged**
