### PR TITLE
Mailserver needs recreation after adding new volume

### PR DESCRIPTION
**Pull request by shyim**
# Description

With just an restart the volume are missing and the follow up command will fail

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the documentation)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aendeavor** [comment]
Am I missing something or does the `docker-compose down` not appear? Is this needed?

**Comment by shyim** [comment]
What do you mean? When the config is changed and you call up it will recreate the container 🤔

**Comment by aendeavor** [comment]
> What do you mean? When the config is changed and you call up it will recreate the container thinking

I'm running Swarm for so long that I don't really remember compose anymore. This update seems fine.

**Review by aendeavor — APPROVED** [review]

**Comment by casperklein** [comment]
@aendeavor is right. If the container is already running, `docker-compose up -d` will do nothing.

`docker-compose down mailserver && docker-compose up -d mailserver` is the correct way IMO.

**Comment by aendeavor** [comment]
> @aendeavor is right. If the container is already running, `docker-compose up -d` will do nothing.
> 
> 
> 
> ~~`docker-compose down mailserver && docker-compose up -d mailserver` is the correct way IMO.~~
> 
> 
> 
> Edit:
> 
> 
> 
> `docker-compose down` is not possible for just a single service. So the best way would just be a complete `docker-compose down; docker-compose up -d`

@casperklein Thank you for clarifying. Could you provide a small follow-up PR?

**Pull request merged**
