### PR TITLE
Add BASH syntax check to linter

### PR DESCRIPTION
**Pull request by casperklein**
# Description

This PR adds an additional (syntax) check for our BASH scripts.

In my experience, `shellcheck` does catch syntax errors, however [the error message may be not as clear](https://github.com/docker-mailserver/docker-mailserver/actions/runs/5089904801/jobs/9148076406#step:4:23) compared to a dedicated syntax check with `bash -n`.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by georglauterbach** [comment]
> In my experience, shellcheck does catch syntax errors, however [the error message may be not as clear](https://github.com/docker-mailserver/docker-mailserver/actions/runs/5089904801/jobs/9148076406#step:4:23) compared to a dedicated syntax check with bash -n.

I got to be honest: I don't actually see any value in adding this check at the moment. To me

```txt
 In ./target/scripts/startup/setup.d/mail_state.sh line 37:
    for SERVICEFILE in "${SERVICEFILES[@]}";; do
    ^-- SC1073 (error): Couldn't parse this for loop. Fix to allow more checks.
                                           ^-- SC1058 (error): Expected 'do'.
```

is absolutely fine, and

```txt
lo.sh: line 3: syntax error near unexpected token `;;'
lo.sh: line 3: `for SERVICEFILE in "${SERVICEFILES[@]}";; do'
```

really adds no new information IMO.

**Comment by casperklein** [comment]
Another point is, the syntax check is pretty fast, less than a second on my setup. It runs before shellcheck and let the lint test fail much faster.
Shellcheck on the other hand takes about 45sec to run.

**Comment by georglauterbach** [comment]
Fair enough! And I mean, if it reall helps others, I don't want to block it anyway :)

**Review by georglauterbach — APPROVED** [review]
LGTM 👍🏼

#3370 is the last PR (together with this one) blocking v13.0.0 - please give it a quick review when you've got time @casperklein :)

**Pull request merged**
