### PR TITLE
ci: Support running tests in parallel (history revised)

### PR DESCRIPTION
**Pull request by polarathene**
# Description

Interactive rebased history of @georglauterbach PR https://github.com/docker-mailserver/docker-mailserver/pull/2822 (_with the intent to better preserve the `git blame` history by staging out the changes a bit more carefully_)

- It has been rebased onto current master, all files have been renamed in the first commit (_including the `clamav.bats` test that was merged since_). Modifications to those renamed tests follow in the next commit.
- `Makefile` changes likewise squashed into single commit and I think I rebased it correctly given new changes in that file since #2822 .

Happy to force-push this over the original PR branch, I've just opted for raising a new PR due to discussions / review feedback there (_I am not sure if it'd be more difficult to track after the force-push with heavy history rewriting_). I've not applied any changes discussed in #2822 feedback.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x]  My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by polarathene** [comment]
Actual file modifications (_since the review page isn't providing proper diffs for some files_) can be found here in [the relevant commit](https://github.com/docker-mailserver/docker-mailserver/pull/2850/commits/b4fc5628991ddd196b66365f9039f72d29672307).

- `test/parallel.1.default_relay_host.bats`
- `test/parallel.2.test_helper.bats` ([has a follow-up commit](https://github.com/docker-mailserver/docker-mailserver/pull/2850/commits/56d11bc7d174e72f8cf2ed9a89deea596c0c03b6) by @georglauterbach that I kept separate)
- `test/parallel.3.dovecot_inet_protocol.bats`
- `test/parallel.3.helper-functions.bats`

---

Review page is still fine for:

- The `Makefile` and Github Actions `generic_test.yml` files.
- The actual two new files that were added:
  - `test/parallel.2.template.bats`
  - `test/serial.setup.sh.bats`

**Comment by georglauterbach** [comment]
Would it be fine if I add some commits on top of this PR? I have some ideas that I wanted to apply to the old PR:)

**Comment by polarathene** [comment]
> Would it be fine if I add some commits on top of this PR? I have some ideas that I wanted to apply to the old PR:)

Yeah should be fine :+1: Feel free to take over this PR and commit away :)

**Comment by georglauterbach** [comment]
@polarathene as I cannot add commits to this PR directly, I opened #2857 which incorporates your changes as well. You can now properly review the changes again and probably close this PR.

**Comment by georglauterbach** [comment]
Closing this in favor of #2857 :)

**Pull request closed without merging**
