### PR TITLE
Remove unusual space from shebang line

### PR DESCRIPTION
**Pull request by casperklein**
# Description

We should stick to "global standards", where the shebang line does not include a space.
The space is absolutely valid, but not widespread used and might look weird to someone new to this project.

Let's discuss.. and merge or withdraw this PR.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by georglauterbach** [comment]
I'm used to the space, but I don't really care, as long as we do it consistently:) This PR does it consistently, so all is well.

**Review by georglauterbach — APPROVED** [review]

**Comment by casperklein** [comment]
I've to admit, that I learned to like it also over the time 😆 But I prefer, that all (my) scripts try to follow the same standards.

**Comment by georglauterbach** [comment]
> I've to admit, that I learned to like it also over the time 😆 But I prefer, that all (my) scripts try to follow the same standards.

I have all my script written _with_ the space 🙈 But this is fine anyway :)

**Comment by polarathene** [comment]
> But I prefer, that all (my) scripts try to follow the same standards.

I'm going to take a wild guess that it'd be more consistent (less files to change) if we kept the space instead for this project :stuck_out_tongue: 

I too prefer the space, and I doubt anyone coming to contribute is going to be tripped up by this concern, I certainly wasn't when I became a contributor and started working with shell scripts (_learned most of that from this project and you two!_ :heart: ).

Likewise, I do not care either way what the project uses, just that we're consistent :+1:

**Review by polarathene — APPROVED** [review]

**Pull request merged**
