### PR TITLE
Rspamd: replace `reject_unknown_client_hostname` with Rspamd `HFILTER_HOSTNAME_UNKNOWN` and make it configurable

### LINKED ISSUE #2970: [BUG] postfix: reject_unknown_client_hostname prevents legitimate mail from being received
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

```Markdown
mailserver  | Jan  1 12:35:19 mail postfix/smtpd[1556]: NOQUEUE: reject: RCPT from unknown[54.240.85.218]: 450 4.7.25 Client host rejected: cannot find your hostname, [54.240.85.218]; from=<010101856d1d37d3-cb9c308b-0000-0000-0000-a21593c7994e-000000@bounce.stripe.com> to=<my-localpart+stripe@example.com> proto=ESMTP helo=<a85-218.smtp-out.us-west-2.amazonses.com>
```
```


### What did you expect to happen?

```Markdown
I expected an option to turn `reject_unknown_client_hostname` off, if it is not considered necessary. I can overwrite the config in the docker-compose, but that feels hacky.
```

### How do we replicate the issue?

```Markdown
I have absolutely no idea. I don't think this happens for all SES mails.
```

### DMS version

latest (d5db200744f1)

### What operating system is DMS running on?

Linux

### Which operating system version?

Archlinux

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
moritz@pan ❯ cat docker-compose.yml                                 docker-mailserver -> master + ? ! $
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
      #entrypoint: ["/bin/sh", "-c", "while true; do sleep 10; done"]
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: moritz.sh
    env_file: mailserver.env
    network_mode: host
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "4190:4190" # MANAGE SIEVE
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./config/:/tmp/docker-mailserver/
      - ./docker-data/dms/config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
mailserver  | Jan  1 12:35:19 mail postfix/smtpd[1556]: NOQUEUE: reject: RCPT from unknown[54.240.85.218]: 450 4.7.25 Client host rejected: cannot find your hostname, [54.240.85.218]; from=<010101856d1d37d3-cb9c308b-0000-0000-0000-a21593c7994e-000000@bounce.stripe.com> to=<my-localpart+stripe@example.com> proto=ESMTP helo=<a85-218.smtp-out.us-west-2.amazonses.com>
```
```


### Other relevant information

_No response_

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_

### LINKED ISSUE #3228: [FR] Replace `reject_unknown_reverse_client_hostname` with Rspamd `HFILTER_HOSTNAME_UNKNOWN` and make it configurable
### Context

See https://github.com/docker-mailserver/docker-mailserver/issues/3224#issuecomment-1500111915.

### Relations

We are using `reject_unknown_reverse_client_hostname` in Postfix's config as a non-configurable default. This is actually mostly fine, but we had requests wanting to make this configurable.

### Description

Now, Rspamd supports something very similar with `HFILTER_HOSTNAME_UNKNOWN`. If the reverse client hostname cannot be found, a (configurable) number is added to the score. We should make this whole setting configurable too.

### Alternatives

N/A

### Applicable Users

Everyone who is using Rspamd OR those that want to configure this setting. I think adding this to the spam score is nice because the score calculation is an overall sum 
where multiple factors are accounted for, so whether an email is spam or not measured by the score should be faily accurate.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

Everything.

### Already Done

Nothing.

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

Please quickly read over #3228 :) Removes `reject_unknown_client_hostname` and (re-)add the test to Rspamd (via `HFILTER_HOSTNAME_UNKNOWN`).

Fixes #3228
Fixes #2970

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by polarathene** [comment]
@GoliathLabs how do you feel about this replacing your Postfix usage from: https://github.com/docker-mailserver/docker-mailserver/pull/2691 ?

Are you using the rspamd feature, if not do you plan to adopt it at some point? Or do you need the feature to remain in Postfix? (_@georglauterbach may still drop it by the end of the year once he switches rspamd on as a default enabled feature_)

**Comment by GoliathLabs** [comment]
> @GoliathLabs how do you feel about this replacing your Postfix usage from: #2691 ?
> 
> Are you using the rspamd feature, if not do you plan to adopt it at some point? Or do you need the feature to remain in Postfix? (_@georglauterbach may still drop it by the end of the year once he switches rspamd on as a default enabled feature_)

I have already used rspamd on one of my older mailserver instances, so I plan to use rspamd with docker-mailserver as well. I wouldn't mind replacing my reject_unknown_client_hostname configuration with the configurable one of rspamd.

**Review by GoliathLabs — APPROVED** [review]

**Review by polarathene — APPROVED** [review]

**Comment by casperklein** [comment]
Correct me if I am wrong. This PR removed the feature `reject_unknown_client_hostname`.  So when not using rspamd, you'll lose that functionality?

**Comment by georglauterbach** [comment]
> Correct me if I am wrong. This PR removed the feature `reject_unknown_client_hostname`.  So when not using rspamd, you'll lose that functionality? If so, why?

We had requests and complaints that this might be too restrictive. If you want me to, I can make this configurable for Postfix again - via an ENV like `POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME=1`. Just let me know :) 

Another rationale is that with Rspamd, this will all be a factor for the spam score metric, which is IMO desirable.

**Comment by casperklein** [comment]
> We had requests and complaints that this might be too restrictive

Not sure, if that represents the majority and justify removal. For me this works [perfectly](https://github.com/docker-mailserver/docker-mailserver/pull/2691#issuecomment-1228366201) and avoids a lot of SPAM.

> I can make this configurable for Postfix again

Yes, please 👍

**Pull request merged**
