### PR TITLE
tests: enable tests that should pass now for Let'sEncrypt

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

Enabled tests that should, according to the comments, pass now.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by georglauterbach** [comment]
@polarathene any idea why these tests do not pass? According to the TODO notes they should...

**Comment by polarathene** [comment]
> @polarathene any idea why these tests do not pass? According to the TODO notes they should...

```
not ok 92 ssl(letsencrypt): Traefik 'acme.json' (*.example.test) in 40796ms
# (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
#  from function `_has_matching_line' in file test/mail_ssl_letsencrypt.bats, line 204,
#  from function `_should_have_valid_config' in file test/mail_ssl_letsencrypt.bats, line 195,
#  from function `_acme_wildcard' in file test/mail_ssl_letsencrypt.bats, line 162,
#  in test file test/mail_ssl_letsencrypt.bats, line 181)
#   `_acme_wildcard' failed
# [   INF   ]  mail.example.test is up and running
# [  DEBUG  ]  2022-04-02 18:51:56  Chagedetector is ready
# 
# -- output differs --
# expected : smtpd_tls_chain_files = /etc/letsencrypt/live/example.test/key.pem /etc/letsencrypt/live/example.test/fullchain.pem
# actual   : 
# --
# 
```

I'd take a wild guess it's a race condition? This test passes for other test cases, and for this one to run, the extraction must have been successful with the correct restart count detected.

I think the failure is due to you only adding the required `_setup_ssl` call for manual certs:

https://github.com/docker-mailserver/docker-mailserver/blob/b93d9708d03cb279c6dd411624165f38197a4f43/target/scripts/check-for-changes.sh#L78-L81

You would add it here too:

https://github.com/docker-mailserver/docker-mailserver/blob/b93d9708d03cb279c6dd411624165f38197a4f43/target/scripts/check-for-changes.sh#L100-L104

And then we can consider the following:

---

### Option A

Technically all we're interested in is updating the config files (_but the method called is private to `_setup_ssl`? Would have to be extracted out above it in `helpers/ssl.sh`? Note the local config vars referenced though_):

https://github.com/docker-mailserver/docker-mailserver/blob/b93d9708d03cb279c6dd411624165f38197a4f43/target/scripts/helpers/ssl.sh#L228-L231

Which might be better to do as `_setup_ssl` will otherwise perform extraction internally redundantly for `acme.json` here:

https://github.com/docker-mailserver/docker-mailserver/blob/b93d9708d03cb279c6dd411624165f38197a4f43/target/scripts/helpers/ssl.sh#L186

### Option B

Alternatively, this entire block can be refactored (_or the equivalent `_traefik_support` method for `_setup_ssl`_):

https://github.com/docker-mailserver/docker-mailserver/blob/35fb744ffb503e6f4e46d11d214d9100f6c17ca8/target/scripts/check-for-changes.sh#L86-L112

The logic is effectively the same as we have here in `_setup_ssl`:

https://github.com/docker-mailserver/docker-mailserver/blob/b93d9708d03cb279c6dd411624165f38197a4f43/target/scripts/helpers/ssl.sh#L99-L124

Except, that doesn't return/set the actual FQDN used as this logic is specific to `check-for-changes.sh`:

https://github.com/docker-mailserver/docker-mailserver/blob/35fb744ffb503e6f4e46d11d214d9100f6c17ca8/target/scripts/check-for-changes.sh#L102-L107

Technically if we extract these lines into two methods for getting the two LetsEncrypt local vars used, then `check-for-changes.sh` could call that too after `_setup_ssl` which will handle the extraction internally instead of `check-for-changes.sh` doing effectively the same?:

https://github.com/docker-mailserver/docker-mailserver/blob/b93d9708d03cb279c6dd411624165f38197a4f43/target/scripts/helpers/ssl.sh#L188-L219

---

I think I could open a PR for that with option B approach, once that's merged this PR should pass :)

**Comment by polarathene** [comment]
[Option B implemented](https://github.com/docker-mailserver/docker-mailserver/pull/2525).

**Comment by georglauterbach** [comment]
Changes implemented in #2525.

**Pull request closed without merging**
