### PR TITLE
Added docker to dependabot.yml config

### PR DESCRIPTION
**Pull request by GoliathLabs**
# Description

I've added the docker package ecosystem to the dependabot.yml, so we can keep track of image updates on a weekly basis.

Fixes #

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [X] If necessary I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
> so we can keep track of image updates on a weekly basis.

Can you give an example? Will this just check the "FROM" statement in our Dockerfile?

**Comment by GoliathLabs** [comment]
> > so we can keep track of image updates on a weekly basis.
> 
> Can you give an example? Will this just check the "FROM" statement in our Dockerfile?

Yes. I know you are using Debian here, which doesn't get version jumps that often, but when one occurs dependabot will notify you.

**Comment by georglauterbach** [comment]
I adjusted the file myself - figured this was the easiest way :)

LGTM 👍🏼

**Review by georglauterbach — APPROVED** [review]

**Comment by GoliathLabs** [comment]
> I adjusted the file myself - figured this was the easiest way :)
> 
> LGTM 👍🏼
> 
> Please note @GoliathLabs that your commits are marked as `unverified`: "The email in this signature doesn’t match the committer email."

Yeah, I still have to add my git email adress to my gpg key. But thanks for pointing that out :)

**Review by wernerfred — APPROVED** [review]
Lets see how useful this gets with the next few releases. IIRC we didnt include it on purpose as we activated dependabot. If it is too noisy or interrupts our workflow we can discuss how to proceed further anyways

**Review by casperklein — APPROVED** [review]
I see no real value in this addition. If the bot tells us, that there is a new major Debian update available and none of us did know this before, we should probably retire 😉

**Comment by GoliathLabs** [comment]
> I see no real value in this addition. If the bot tells us, that there is a new major Debian update available and none of us did know this before, we should probably retire 😉

Nonetheless it probably will be the first to create a pull request regarding this

**Comment by georglauterbach** [comment]
While I'd normally be hesitant to merge this into the Shell code base, the very worst this could do is open a useless PR. At best, we future-proof the image (for the very far future). I'm rather confident that this will not negatively impact DMS, and we can easily revert it if necessary.

**Pull request merged**
