### PR TITLE
docs: Change `edge` version links to `latest` + fix links intended as relative not absolute

### PR DESCRIPTION
**Pull request by jrpear**
# Description

Change hard-coded links to point to the latest release rather than edge. Also change a few hard-coded links to be relative where I thought it made sense.

Finish addressing #3173

I don't know how the description on docker hub is maintained, maybe that needs a manual update. The github project description will certainly need a manual update.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by jrpear** [comment]
Unrelated comment: I've been going through lots of the code, I appreciate how well commented it is and all of the links to relevant issues, I've come across a lot from @polarathene. Makes me want to work with this project more!

**Review by polarathene — CHANGES_REQUESTED** [review]
Thanks for tackling contributing this update too! :heart: 

<details>
<summary>Original feedback (resolved)</summary>

Looks great :sunglasses: I've been a bit laxed on doc reviews these days and not enforced conventions introduced for consistently managing links.

The preference was to always have doc links use references with relative paths and prefix those references with `docs-`, usually bundling all those at the bottom of each docs page, but over time some have been co-located closer to the content which is ok too.

I've changed your `latest-docs` to `docs-latest` to stick with that convention.

---

You just need to update the workflow file so we also set the canonical link to `latest` instead of `edge` :+1: 

Whoops, just realized I made that a little bit annoying for you by committing the suggestion myself, sorry about that :grimacing: Remember to pull this branch first before committing a new change!

</details>

**Comment by polarathene** [comment]
> Also change a few hard-coded links to be relative where I thought it made sense.

Fantastic, thanks for catching those! :grinning: 

> I don't know how the description on docker hub is maintained, maybe that needs a manual update.
> The github project description will certainly need a manual update.

I don't have rights to do either of those AFAIK. @wernerfred might?

Otherwise you'll need to wait on @georglauterbach I think, who is presently on vacation (_and will hopefully make a best effort to remember they're on vacation, and wait until they've returned as there is **no rush**_ :stuck_out_tongue: ).

---

> Unrelated comment: I've been going through lots of the code, I appreciate how well commented it is and all of the links to relevant issues

We certainly try! :muscle: 

It's something I tend to embrace a bit too excessively at times for the benefit of future maintainers (_and sometimes future me who forgets_ :joy: ) as there is quite a bit of niche knowledge and decisions in the project.

I have gotten a bit more lazy with formatting merge commit messages on PRs, so `git blame` should help track down the relevant PR for better details / insights :+1:

**Review by polarathene — APPROVED** [review]

**Comment by polarathene** [comment]
Cheers, I'll wait for another approval for this change before merging.

**Comment by jrpear** [comment]
Yeah, I believe you're right about the purpose of canonical links. Also the old versions of the docs will still have `edge` as their canonical versions unless we manually commit a change to those. Happy to add that to this PR or make another if that seems worthwhile.

**Comment by jrpear** [comment]
> There's the shell scripts that glues most of the project together, but I can't say that's particularly enjoyable sweat_smile or researching parts of the project to troubleshoot / improve something (scripts aside). I know I've sunk a tonne of time going down rabbit holes on niche topics just to fix some config settings

I have a strange fondness for bash haha. Before I found this project, I spent probably 50 hours trying to create something which was nearly identical to dms with bash, systemd, and systemd-machined.

**Comment by polarathene** [comment]
> Also the old versions of the docs will still have `edge` as their canonical versions unless we manually commit a change to those.

That's a pretty good point :sweat_smile: 

We could do that in a separate PR I think (_keep that noise separate from main focus of this PR_). (**EDIT:** As noted in 2nd section, this is probably not a PR we could review properly :disappointed: )

That reminds me of [this issue with `v11.1`](https://github.com/docker-mailserver/docker-mailserver/issues/2688). Bit of a hassle (_to build locally and adjust correctly_) presently since it needs to be built like it would be via the CI for that tagged commit, but our CI workflow isn't setup for manual trigger of the workflow with inputs to support that (one fix).

I was working on enabling manual trigger in the CI workflow but didn't get around to finishing it.

At the same time, I'm kind of tempted to archive our older versions of docs at some point as we can't realistically support them the older they get.

Also I don't think the preview deployments are ever routinely removed either and I probably should look into sorting that out :grimacing: 

---

> Happy to add that to this PR or make another if that seems worthwhile.

I'm a bit concerned about the diff size. It's probably not something I can review properly, and we can only trust ignoring large diffs from maintainers :sweat_smile: 

I could perhaps instead run a script to apply the change myself. (**EDIT: This is probably the best approach**)

Alternatively if we improve the workflow to support manual triggering of builds, it could be done that way too (_probably not a good idea as running a newer version of the docs generator will probably break old docs with deprecated syntax / features, I know that happened at some point_).

---

> I have a strange fondness for bash haha.
> Before I found this project, I spent probably 50 hours trying to create something which was nearly identical to dms with bash

Oh wow! You'd be very welcome to help with the scripts if you're comfortable :grin: 

The other two active maintainers are very good with bash, and we can all advise on the project if you have any questions.

**Comment by wernerfred** [comment]
> I don't have rights to do either of those AFAIK. @wernerfred might?

Nope sorry. But that reminds me that we might need a list regarding all tools/portals we use and who is responsible/has permissions for what (github, dockerhub, netlify, ...)

**Review by wernerfred — COMMENTED** [review]
I recall a long discussion we had when introducing the versioned docs. We left out latest (or switched to edge) on purpose. Rethinking this now imho it makes sense the way it is now as we also publish a `latest` tag together with the latest release. Only linking to specific docs site might break in future when sites gets removed or moved between sections. That is something that won't happen with strickt versioned docs. 

Looking at the `edge` docs we have a small tooltip that this is the latest documentation but not the latest stable one. Should we add a hint like this to the `latest` docs page as well stating that this is not the latest docs but the latest stable one?

Waiting for your opinion on that and if you both disagree with me i am happy to approve anyways.

Thanks @jrpear for putting this together and @polarathene i agree 100% on this "unrelated" comment:
>  I've been going through lots of the code, I appreciate how well commented it is and all of the links to relevant issues, I've come across a lot from @polarathene.

**Comment by polarathene** [comment]
> Only linking to specific docs site might break in future when sites gets removed or moved between sections. That is something that won't happen with strickt versioned docs.

Hmm? Our docs are still versioned and you can link to them.

Recent contributions from @jrpear has introduced a `latest` alias to the current release (_all handled via the CI when a release is tagged_).

The plan was to default to directing users to those docs instead of `edge`, as we've received issues about users not paying attention to the version selector (_which is understandable to miss when new to our docs_), pulling `:latest` and getting confused by what the `:edge` docs say as those changes / features aren't yet released (_v12 has been a rather long cycle with some bigger changes_ :sweat_smile: )

---

I can't recall much about that earlier discussion, perhaps it related to `edge` docs reflecting the `master` branch as we don't have any separate dev branch.

I think our users are more likely to encounter the mismatch with image registries and the default `:latest` pull experience, than they are with the git repo mismatching the default docs version we link to?

**Comment by polarathene** [comment]
> Looking at the `edge` docs we have a small tooltip that this is the latest documentation but not the latest stable one. Should we add a hint like this to the `latest` docs page as well stating that this is not the latest docs but the latest stable one?

AFAIK this is from refactoring that part of the docs during v12 by @georglauterbach 

I don't think you meant tooltip (popover / hover), but the admonition (coloured boxed content) we have on the main docs page?

Once we release v12, the `latest` will also inherit that. It's a bit difficult to bring back to previous docs as they build off tags, we could inject it directly into the existing HTML content on `gh-pages` branch, but the markup/CSS may differ from earlier doc versions.

---

An easier fix is to remove releases after they're a certain age, simplifying the version selector to recent versions only. The markdown would still be accessible via git history on `gh-pages`, and running them locally to access in the browser should be doable easily enough with something like `caddy`.

**Comment by wernerfred** [comment]
> Hmm? Our docs are still versioned and you can link to them.

Let me give an example:

You link to `dms.docs/latest/some-site-a` which is an alias for `dms.docs/11.3/some-site-a`

Now in v12 site-a gets moved to site-b

Someone later in time using `dms.docs/latest/some-site-a` would get a `404` whereas someone using `dms.docs/11.3/some-site-a` would still be presented with the initial linked (but now outdated) docs.

This even gets more complicated if not the site name switches but huge amount of the content is changed. Refs to this docs in old Issues or Posts will link to docs that might be completely out of context content wise.

Do you get my point or am i overseeing something?

**Comment by wernerfred** [comment]
> I don't think you meant tooltip (popover / hover), but the admonition (coloured boxed content) we have on the main docs page?

Yes i meant that admonition

> Once we release v12, the `latest` will also inherit that. It's a bit difficult to bring back to previous docs as they build off tags, we could inject it directly into the existing HTML content on `gh-pages` branch, but the markup/CSS may differ from earlier doc versions.

Thanks for clarifying, then i have no issue here. Just one further question. Will `latest` inherit the same box/info with `v12`? Asking because it states that `edge` is the default one but as i understand it it should be switched to `latest` then, correct?

**Comment by polarathene** [comment]
> This even gets more complicated if not the site name switches but huge amount of the content is changed. Refs to this docs in old Issues or Posts will link to docs that might be completely out of context content wise.
> 
> Do you get my point or am i overseeing something?

I understand that issue, but that isn't different to defaulting to `edge`, nor is it resolved even if we did change to manually updating URLs each time to the current release tag, as users may still do the same with `edge` doc links, or `latest` if we keep that around.

`latest` will be just as prone to the issue as `edge`, and I can see how that may be more prone to happening than `edge` would, but I have often seen this done with `edge` links when users are actually discussing released versions. I personally try to use versioned links when relevant but it's often convenient to just grab the URL forgetting what version you're on (_in which case I'd end up with `edge`, and now `latest`, so nothing really changes - that's user error_).

---

> Will `latest` inherit the same box/info with `v12`?

- The version selector will have two entries for the latest release (`latest` + actual tag/version). Behind the scenes `latest` is just a symlink to the current release version docs folder.
- The admonition is not built dynamically and won't differ from `edge` docs. Presently it's hard-coded to `edge` and the description makes a mention of that, while **this PR changes the mention and URL versions to `latest`**, thus our `edge` docs will also reference `latest` in the admonition.

---

I think those were the answers you were after?

If you're still concerned about `latest` and would like a better solution, I believe I brought this concern up when we first introduced the docs.

Github Pages doesn't support redirects, but our preview service (Netlify) does. If we no longer used Github Pages (_to publish, the `gh-pages` branch could still be the source content served_), Netlify could redirect to the latest release instead, thus any `latest` URL should update to the current release version, and then any URL copied would be versioned correctly.

Only drawback is the host would change from Github to Netlify, breaking all the existing links (_unless we kept serving them with a banner about the new home_). Obviously not ideal, but that gets worse the longer we stay on Github Pages (_which we've used for approx 2 years now?_).

At the same time, I'd like to discard some older doc versions which'd have the same effect :sweat_smile: (_on the plus side, with Netlify I have a 404 page that would at least better communicate to users about content being unavailable and direct them to the newer docs, GH pages last I checked didn't support 404 pages that well_).

**Review by wernerfred — APPROVED** [review]
Thanks for clarifying!

In fact i would like the option you mentioned with netlify the most (from a technical and UX perspective) but regarding the dockerhub discussion i would prefer to stick with as many onboard solutions as possible. Imagine netlify cancelling their OSS plans then we are totally screwed ⚠️

**Comment by georglauterbach** [comment]
Since today is [Nyepi](https://en.m.wikipedia.org/wiki/Nyepi) on Bali, and I alread spent a lot of time sleeping and being in the sun (since I am not allowed to go outside), I can warrant 10mins on GH even though I'm on vacation 😂🙂

---

The PR looks good! I'd stay with GH because it is unlikely we loose the ability to show out docs due to cancelled OSS plans.

---

@jrpear we're always looking for contributors, moderators and in a best-case scenario, maintainers.

If you are interested in DMS, I'd start by inviting you to the moderators team first. This will give you the ability to adjust issues and PRs. You'd also have access to the private discussions repo. Thereafter, I'd add you to the maintainers team :)

Just tell me whether you're interested 🙂

**Review by georglauterbach — APPROVED** [review]

**Comment by georglauterbach** [comment]
PS: I will adjust the DockerHub README.

**Comment by jrpear** [comment]
> @jrpear we're always looking for contributors, moderators and in a best-case scenario, maintainers.
> 
> If you are interested in DMS, I'd start by inviting you to the moderators team first. This will give you the ability to adjust issues and PRs. You'd also have access to the private discussions repo. Thereafter, I'd add you to the maintainers team :)

Yeah, I'd be happy to help moderate!

> PS: I will adjust the DockerHub README.

Great! Do you have permission to update the GitHub project description too? That still links to edge.

**Comment by georglauterbach** [comment]
> Yeah, I'd be happy to help moderate!

You should have an invitation :)

> > PS: I will adjust the DockerHub README.
>
> Great! Do you have permission to update the GitHub project description too? That still links to edge.

Done :D

**Pull request merged**
