### PR TITLE
Add dependabot for github actions and git submodules

### PR DESCRIPTION
**Pull request by wernerfred**
Add [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) configuration for github actions. Dependabot will periodically (here: weekly) scan if there are newer versions in the upstream repositories of our used github actions available and automatically add a PR to update the dependency.

Might be that a maintainer needs to turn on dependabot checks in the repository dependency settings.

### CODE REVIEW

**Comment by wernerfred** [comment]
We can [set default reviewers and labels](https://docs.github.com/en/github/administering-a-repository/customizing-dependency-updates), too. Just tell me who/which would fit and I will update the configuration.
Maybe @radicand and @wernerfred as reviewers and area/dependency and pr/needs review as the labels

**Comment by wernerfred** [comment]
Added git submodules to the configuration. We can define the previous mentioned reviewers/assignees/labels per ecosystem so give me a hint what should be done/used on PRs for git submodules

**Comment by aendeavor** [comment]
> Add [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) configuration for github actions. Dependabot will periodically (here: weekly) scan if there are newer versions in the upstream repositories of our used github actions available and automatically add a PR to update the dependency.
> 
> Might be that a maintainer needs to turn on dependabot checks in the repository dependency settings.

I have turned Dependabot on and the security alerts too. The maintainers team will receive notifications.

> We can set default reviewers and labels, too. Just tell me who/which would fit and I will update the configuration.
> Maybe @radicand and @wernerfred as reviewers and area/dependency and pr/needs review as the labels

You could set @radicand @wernerfred and @aendeavor for this.

> Added git submodules to the configuration. We can define the previous mentioned reviewers/assignees/labels per ecosystem so give me a hint what should be done/used on PRs for git submodules.

I'm not sure I get that. What does that now do for the submodules? Our submodules are _a bit_ outdated, looking at Bats (@martin-schulze-vireso knows more)

> EDIT: Apart from this PR we should add an area/dependency label in general to the project

I've gone ahead and added it.

**Comment by wernerfred** [comment]
> I'm not sure I get that. What does that now do for the submodules? Our submodules are _a bit_ outdated, looking at Bats (@martin-schulze-vireso knows more)

The submodule configuration will check if there are newer versions of used submodules available and also create a PR to update them (doesn't need to be merged and if there is a specific reason also can be set to be ignored).

The other sentence means that dependabot can assign different users and add different labels if the PR is about update on a submodule than on a github action.

**Comment by aendeavor** [comment]
Please remove the submodule ecosystem for now. When we have updated to new latest version of Bats, we can get back to this. For now, this would introduce a lot of noise:)

**Review by aendeavor — APPROVED** [review]

**Comment by aendeavor** [comment]
Since you're a maintainer now, I thought it'd be appropriate for you to merge your PR yourself :) I've already labeled it accordingly.

**Comment by wernerfred** [comment]
Sadly the action failed:
https://github.com/docker-mailserver/docker-mailserver/runs/1723082956?check_suite_focus=true#step:8:674

The build-and-test-image works fine but the build-multiarch-and-push leads to an authorization error. @radicand @aendeavor any ideas?

**Comment by radicand** [comment]
Given this shouldn't have affected the build workflows at all, I'd say re-run as a first debug step.

**Comment by aendeavor** [comment]
This was most certainly my fault. I removed the bot responsible for pushing from the owners team because we had this in mind earlier. This most likely lead to insufficient permissions. I have now corrected that and re-run the workflow.

**Pull request merged**
