### PR TITLE
Fix several typos

### PR DESCRIPTION
**Pull request by casperklein**
# Description

Fix typos..

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by georglauterbach — APPROVED** [review]
👍🏼

**Comment by casperklein** [comment]
Tests failing again 😠

**Comment by georglauterbach** [comment]
> Tests failing again [sporadically](https://github.com/docker-mailserver/docker-mailserver/actions/runs/3874896684/jobs/6606740206) 😠
> 

Was #2988 already in the first commit?

**Review by polarathene — APPROVED** [review]
Did you use a tool to identify these, or you were actually scanning through these documents finding typos manually? (_or some syntax highlight/lint feature in IDE?_) :thinking:

**Comment by casperklein** [comment]
I used good old `grep` together with a file that contains common typos:

`grep -F -f common-typos.txt -R docker-mailserver`

**Pull request merged**
