### PR TITLE
ci(tests): Add timing measurement to output

### PR DESCRIPTION
**Pull request by polarathene**
# Description

Extracted from [this open PR commit](https://github.com/docker-mailserver/docker-mailserver/pull/2245/commits/8ebbca3f24dea34375a4fe61232b4bce77da2b30) as it's not required for that PR.

@NorseGaud added this as an improvement for the test logs to include time measurements.

---

For the CI there is an a `CI` ENV that is detected so `bats` uses the `TAP` formatter. If you'd like to swap the test number with the fancy tick/cross symbols for pass/fail, we can additionally add `--pretty` (or --formatter pretty).

Version 1.5.0 of `bats` also [released about a week ago](https://github.com/bats-core/bats-core/releases/tag/v1.5.0).

Let me know if you'd like either of those additions added.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by casperklein — APPROVED** [review]

**Review by wernerfred — APPROVED** [review]

**Comment by NorseGaud** [comment]
❤️ when I get back from travel I can help. Thanks for handling this

**Comment by polarathene** [comment]
> when I get back from travel I can help

No worries :)

It's mostly done, I'm just trying to get slim down the PR for reviewers. Still more to split out, it'll probably just be left as the change to `DMS_DOMAIN_NAME` in your original PR so no one needs to trawl through the large discussion iterating on the PR when looking through git history for maintenance/info.

I want to help you get your other PRs tackled like encryption :grinning: 

But feel free to add a PR with `--pretty` and updating bats to 1.5.0 as the other maintainers didn't provide any input towards adding those changes. I know you were looking into some other flags for bats with error output I think too that was waiting on 1.5.0, if those are helpful by default maybe add those too :)

**Comment by NorseGaud** [comment]
> > when I get back from travel I can help
> 
> No worries :)
> 
> It's mostly done, I'm just trying to get slim down the PR for reviewers. Still more to split out, it'll probably just be left as the change to `DMS_DOMAIN_NAME` in your original PR so no one needs to trawl through the large discussion iterating on the PR when looking through git history for maintenance/info.
> 
> I want to help you get your other PRs tackled like encryption 😀
> 
> But feel free to add a PR with `--pretty` and updating bats to 1.5.0 as the other maintainers didn't provide any input towards adding those changes. I know you were looking into some other flags for bats with error output I think too that was waiting on 1.5.0, if those are helpful by default maybe add those too :)

Yeah, 1.5.0 is taking forever :\

**Comment by polarathene** [comment]
> Yeah, 1.5.0 is taking forever :\

? It was released about a week ago.

**Comment by NorseGaud** [comment]
> > Yeah, 1.5.0 is taking forever :\
> 
> 
> 
> ? It was released about a week ago.

Cool, haven't looked in several

**Pull request merged**
