### PR TITLE
release: version v10.3.0

### PR DESCRIPTION
**Pull request by polarathene**
# Description

This PR marks the feature freeze phase for `v10.3.0` release.

The current `:edge` image will be tested for roughly one week and if no bugs get reported, `v10.3.0` will be released. During this testing period, only PRs that do not change functionality will be merged.

**If you want to support us, give the latest `:edge` image a try and report any issues you might (hopefully not) encounter back to this PR.**

**Feature freeze is in place until _29 Nov 2021_**. Documentation updates may be merged.

---

I've not included all PRs since the previous release. I'm not entirely familiar with what qualifies. I didn't mention my PRs related to tests only, or rather minor improvements for example, nor anything separate from the image like our CI or issue templates.

## Type of change

- [x] Release

## Release-Checklist:

- [x] Update CHANGELOG.md
- [x] Update version in VERSION
- [x] Draft release

### CODE REVIEW

**Comment by georglauterbach** [comment]
Feel free to add what you think is appropriate to the changelog based upon what you see (which PRs) in the milestone for `v10.3` :)

**Comment by polarathene** [comment]
I'm good for v10.3 release once the following are merged:

- [ ] [#2260 - fix: check-for-changes.sh should not fall out of sync with shared logic](https://github.com/docker-mailserver/docker-mailserver/pull/2260)
- [ ] [#2280 - refactor: Internal HOSTNAME and DOMAINNAME configuration](https://github.com/docker-mailserver/docker-mailserver/pull/2280)
- [ ] [#2286 - tests(feat): Complete rewrite of letsencrypt tests](https://github.com/docker-mailserver/docker-mailserver/pull/2286)

The PR that was being split out into multiple PRs has two changes not yet extracted (_The refactored hostname test, and change for `DOMAINNAME` to `DMS_DOMAINNAME` or similar_), but I don't think either of those needs to block the release.

**Comment by polarathene** [comment]
All PRs are merged that were being waited on. I've updated the original PR message to have the usual release message, with a date of 29th Nov 2021 (feel free to adjust that).

**Review by georglauterbach — APPROVED** [review]

**Comment by georglauterbach** [comment]
@docker-mailserver/maintainers we'll need one more review on this for the release tomorrow :)

@polarathene would you like to release `v10.3.0` on GitHub too?

**Comment by casperklein** [comment]
@georglauterbach Approval should be given **after** successful testing 😉

**Review by casperklein — APPROVED** [review]
I had no problems in my setup, within the last 7 days with `:edge` 👍

**Comment by georglauterbach** [comment]
Was just a reminder :D
Been testing `:edge` for 14 days, haven't had any problems either.

**Comment by casperklein** [comment]
Did you pull `:edge` or build the image in the meantime? Otherwise, there were commits between14. and 21. November that you would have missed testing.

**Comment by georglauterbach** [comment]
> Did you pull `:edge` or build the image in the meantime? Otherwise, there were commits between14. and 21. November that you would have missed testing.

Pulled `:edge` several times, no worries:)

**Comment by polarathene** [comment]
BTW, a big thank you to @georglauterbach and @casperklein for all the reviews for the big PRs I put out for this release, and to @NorseGaud for the initial work they were based off :+1: 

> @polarathene would you like to release `v10.3.0` on GitHub too?

I am not familiar with the process or if I have those maintainer permissions to do so?

I'm good if someone else would like to handle the release, but open to taking a shot at it. Is it just drafting a GH release with changelog contents paired with a git tag, and the CI handles the rest?

**Comment by casperklein** [comment]
> Is it just drafting a GH release with changelog contents paired with a git tag, and the CI handles the rest?

Yes.

**Comment by polarathene** [comment]
Alright, [I think I did it correctly](https://github.com/docker-mailserver/docker-mailserver/releases/tag/untagged-4f85adfc1cae9b22a88c). If a maintainer wants to give a :+1: that I handled that right I'll go ahead and publish :)

[Looking at timezones](https://www.timeanddate.com/time/map/), it's roughly almost midnight at UTC+0 for the 29th, that covers EU but not USA? Not sure if there is any policy for timezone, it's nearing midday for me in NZ.

**Comment by casperklein** [comment]
> go ahead and publish :)

Make sure, to merge this PR first.

**Pull request merged**
