### PR TITLE
Write docs on how to write docs

### PR DESCRIPTION
**Pull request by williamdes**
# Description

I added documentation on how to just make it work to write and preview documentation

Preview: https://pullrequest-2129--dms-doc-previews.netlify.app/contributing/documentation/

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by wernerfred** [comment]
Linking @polarathene here, as he might already have some guidelines to add

**Comment by polarathene** [comment]
I have a WIP contributor doc from earlier this year to finish at some point, but this looks fine as a helpful doc page in the meantime! :)

Not sure about the native python setup since we're docker focused already, and Python 2.x being deprecated last I heard? (_just due to the version cited, I'm sure it works just as well with 3.x_). Would drop a little repetition.

You don't need to be in the `docs/` subdirectory for the container approach, just changing the volume mount from `${PWD}` to `${PWD}/docs` would let you run from the project root too, but I guess we'd point that out in the same way :man_shrugging: 

LGTM.

**Review by polarathene — APPROVED** [review]
Cheers for the contribution! :grin:

**Comment by williamdes** [comment]
> Cheers for the contribution!

Happy to help ;)

> but I guess we'd point that out in the same way

Yup, for docker it could be avoided but then the sentence should say that you need to be at the root of the repository ^^
I used the same method as for the pip method so the steps stay the same

**Comment by wernerfred** [comment]
@all-contributors add @williamdes for docs

**Pull request merged**
