### PR TITLE
issues/1982: default to using container, if it exists + more

### PR DESCRIPTION
**Pull request by NorseGaud**
# Description

From the various discussions and investigations I've done (https://github.com/docker-mailserver/docker-mailserver/issues/1982, etc), it seems like using the container, if available, should be the default.

Also, if not available, and if we use the default image, it should check if the config path exists or is empty.

I've also changed the docker_image/_container commands into one.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
Some actions like `email delete` require a running container. From a quick look I would say, it's not guaranteed with your solution. 

If no container is running, a new one is created, with missing mounts (maildata.. etc.) ?

**Comment by NorseGaud** [comment]
> Some actions like `email delete` require a running container. From a quick look I would say, it's not guaranteed with your solution.
> 
> If no container is running, a new one is created, with missing mounts (maildata.. etc.) ?

I could add logic that ensures those other directories are available when using the temporary container. Good catch

**Comment by casperklein** [comment]
> I could add logic that ensures those other directories are available when using the temporary container. Good catch

That's not easy, as you don't know how some does mount the directorys. Some use volumes, some bind mounts.

Beside parsing `docker-compose.yml` which I think is a really bad idea, I don't have a solution for that.

Please see also my comment [here](https://github.com/docker-mailserver/docker-mailserver/pull/1874#issuecomment-809781531).

**Comment by NorseGaud** [comment]
> > I could add logic that ensures those other directories are available when using the temporary container. Good catch
> 
> That's not easy, as you don't know how some does mount the directorys. Some use volumes, some bind mounts.
> 
> Beside parsing `docker-compose.yml` which I think is a really bad idea, I don't have a solution for that.
> 
> Please see also my comment [here](https://github.com/docker-mailserver/docker-mailserver/pull/1874#issuecomment-809781531).

I've added code that I believe covers volumes or host level paths.

Glad to hear you didn't like `docker-compose.yml` too :) I almost went that route but it seemed weird to me too.

**Pull request closed without merging**
