### PR TITLE
tests: Wait until container is not in starting state anymore, before running health check

### PR DESCRIPTION
**Pull request by casperklein**
# Description

It seams, that Docker does not start a container immediately, after successfully running the `docker run..` command. Therefor the 30 seconds wait time for the health test can be to low. ~Hopefully, adding three more seconds solve that issue.~

Fixes: https://github.com/docker-mailserver/docker-mailserver/actions/runs/3162276455/jobs/5148743130#step:5:227

This fix now waits, until docker itself reports, that the container is not in the starting state anymore.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by georglauterbach — APPROVED** [review]
While not pretty, I hope this does the job :)

**Comment by casperklein** [comment]
> While not pretty, I hope this does the job :)

I decided for another approach, which hopefully will be bullet proof now.

**Review by polarathene — APPROVED** [review]
Much nicer :+1:

**Review by georglauterbach — APPROVED** [review]
Indeed, much better - LGTM 👍

**Pull request merged**
