### PR TITLE
`README.md`: add git statistics

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

I came across this visualization recently and found it neat; it gives users an idea of how well this project is actually maintained, and it looks nice. It's not something super important; if you think it does not fit well into the project, or you have other good reasons to reject it, please let me know - I don't mind seeing this rejected, just wanted to bring it up.

Under the hood, we're using [Axiom](https://repobeats.axiom.co/).

---

Here is the link to the branch: <https://github.com/docker-mailserver/docker-mailserver/tree/git-statistics>

Here is what it looks like:

git_stats

## Type of change

- [x] This change is a documentation update

## Checklist

- [x] My code follows the style guidelines of this project

### CODE REVIEW

**Review by polarathene — APPROVED** [review]
I think most of that is already presented by the repo "Insights" tab? This is just a nicer visual summary?

I'm fine with it, but I don't know if it provides much value to users in the README 🤷‍♂️

**Comment by georglauterbach** [comment]
It's nothing completely new, indeed, just a nice visual presentation.

**Comment by casperklein** [comment]
I am not sure if these stats are correct. I noticed the top contributors jpsanchezl10 and UltraCoderRU. jpsanchezl10 opened an [issue](https://github.com/docker-mailserver/docker-mailserver/issues/3488) in 2023 and for UltraCoderRU I couldn't find anything at all. Do I miss something here?

**Comment by polarathene** [comment]
> UltraCoderRU I couldn't find anything at all

The `CONTRIBUTORS.md` isn't too helpful at times with how sort order shuffles between updates 🤷‍♂️ 

The user was listed in the file though, and searching for them on PR history with `author:UltraCoderRU` does provide this:
- https://github.com/docker-mailserver/docker-mailserver/pull/3925

[No PRs for `jpsanchezl10`](https://github.com/docker-mailserver/docker-mailserver/pulls?q=is%3Apr+author%3Ajpsanchezl10), only [3 issues raised](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue+commenter%3Ajpsanchezl10).

So yeah that is odd and misleading.

I personally don't find value in the metric, similar to how commit frequency / size doesn't convey much (_since before we adopted squash merge for PRs that was a common factor for "top" contributors ranking in the past_).

**Comment by georglauterbach** [comment]
That's odd, I agree. I don't like when something like this is there right from the start.

**Pull request closed without merging**
