### PR TITLE
release: `v11.1.0`

### PR DESCRIPTION
**Pull request by polarathene**
# Description

This PR marks the feature freeze phase for the `v11.1.0` release.

The current `:edge` image will be tested for roughly one week and if no bugs get reported, `v11.1.0` will be released. During this testing period, only PRs that do not change functionality will be merged.

**If you want to support us, give the latest `:edge` image a try and report any issues you encounter back to this PR.**

Documentation updates may be merged. **Feature freeze is in place until 22 June 2022**.

## Type of change

- [x] Release

## Release-Checklist:

- [x] Update CHANGELOG.md
- [x] Update version in VERSION
- [x] Draft release

### CODE REVIEW

**Comment by polarathene** [comment]
Big thank you to @georglauterbach and @casperklein for all the reviews they've provided to my burst of PRs recently, very much appreciated :+1:

**Comment by georglauterbach** [comment]
Feature freeze can now be put in place.

**Comment by polarathene** [comment]
> drafting the release

Is Github release drafts automatically generating that contribution list these days? That's pretty cool :sunglasses:

**Comment by georglauterbach** [comment]
> > drafting the release
> 
> Is Github release drafts automatically generating that contribution list ("What's changed") these days? That's pretty cool sunglasses

Yes, and we could even use this format in out CHANGELOG. I'm a bit tired of changing the format :D Any objections?:)

**Review by georglauterbach — APPROVED** [review]

**Comment by polarathene** [comment]
@georglauterbach Sorry, I am not sure why as I merged this PR before hitting the publish release button, but it seems to have skipped the merge commit and tagged the wrong commit? Can we fix that still?

**Comment by georglauterbach** [comment]
> @casperklein @georglauterbach Sorry, I am not sure why as I merged this PR before hitting the publish release button, but it seems to have skipped the merge commit and tagged the wrong commit? Can we fix that still?
> 
> I guess when @georglauterbach drafted the release with the tag, it was at the time the previous commit was the latest and for some reason the release was setup to tag that commit? (I thought it tagged the branch HEAD commit upon publishing)
> 
> Oh, it seems that the commit was tagged already. I was wondering why no workflow to build and publish was running..
> 
> ```shell
> # On local repo clone prior to the merge from this PR:
> $ git log --tags --simplify-by-decoration --pretty="format:%ai %d"
> 
> 2022-06-15 12:31:58 +0200  (tag: v11.1.0, origin/master, origin/HEAD)
> ```

Typically, the release targets the latest commit on the given branch, in out case `master`, so the most likely case here is that you accidentally released `v11.1.0` before you merged this PR? It makes sense that before the merge, the release pointed to the commit before this PR merged into `master`.

> So we need to rewrite history with the tag I take it? I think tags have a separate history, so it might not be too bad? [It is still discouraged](https://stackoverflow.com/questions/25849019/move-tag-one-commit-ahead/25849917#25849917), but I think the consequence right now might not affect maintainers or users much...?

Seems reasonable to me.

**Comment by polarathene** [comment]
> Typically, the release targets the latest commit on the given branch, in out case `master`, so the most likely case here is that you accidentally released `v11.1.0` before you merged this PR?

The `git log` shared was a clone I had prior to doing anything yesterday, note the date of the tag. I think that was around the accidental release workflow you mentioned and cancelled?

Unless the log is showing a tag to a remote origin and the release tag is tied to the date of the commit (_**EDIT:** Just looked at the commit date, same timestamp... my bad_).

I definitely merged this PR before publishing the release, but I may have had it opened it a separate tab prior... Perhaps the web frontend requested to tag the last commit it was aware of rather than HEAD commit :sweat_smile: 

Either way apologies for not paying enough attention, thanks for resolving it! :heart:

**Pull request merged**
