### PR TITLE
Streamline COPY statements in Dockerfile

### PR DESCRIPTION
**Pull request by casperklein**
# Description

Nothing big.. Just streamlining the `COPY` usage In `Dockerfile`. Some statements used `./`, while some did not.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by polarathene — APPROVED** [review]

**Review by georglauterbach — APPROVED** [review]

**Review by georglauterbach — APPROVED** [review]

**Comment by georglauterbach** [comment]
@polarathene I'm a bit afraid that #2729 shows that there still are timing-related problems with our tests, but test failures are now happening in PRs for which tests should run fine. Anything we can do here as a follow-up?

**Comment by georglauterbach** [comment]
See https://github.com/docker-mailserver/docker-mailserver/pull/2752#issuecomment-1230286950.

**Review by wernerfred — APPROVED** [review]

**Comment by polarathene** [comment]
> but test failures are now happening in PRs for which tests should run fine. Anything we can do here as a follow-up?

Can you link to the PR with failing test?

I saw [this one](https://github.com/docker-mailserver/docker-mailserver/runs/8071703686?check_suite_focus=true), but not sure if this was due to the issues you fixed in later commits? (_due to a package you had omitted from the build_)

---

Early setup of `test/tests.bats` is the area that's been mostly sensitive to timing.

There's also a `check-for-changes.sh` test for `remove_lock()` which failed one time likely due to timing issues, but the method didn't output anything to log when the conditions were not met IIRC. If it happens again, I'd patch it, otherwise when I have time later in the year I would like to tackle switching back to `flock()`.

**Comment by casperklein** [comment]
> See [#2752 (comment)](https://github.com/docker-mailserver/docker-mailserver/pull/2752#issuecomment-1230286950).

Overlooked that. I thought the comment was about the failing tests :worried:

**Comment by georglauterbach** [comment]
> > See [#2752 (comment)](https://github.com/docker-mailserver/docker-mailserver/pull/2752#issuecomment-1230286950).
> 
> Overlooked that. I thought the comment was about the failing tests worried

No worries. Due to the large feedback, I will provide separate PRs and close #2752 :)

**Pull request merged**
