### PR TITLE
update: bump Fail2Ban version to v1.0.2

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

Bump F2B version to the next major version (v1.0.2). Same as #2903 which got reverted due to release of v11.3.1.

## Type of change

- [x] Component update
- [x] _possibly_ breaking change (nothing that is breaking observed for DMS yet though)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by polarathene — APPROVED** [review]

**Comment by polarathene** [comment]
@casperklein friendly ping :)

Not sure if you missed this or plan to review / comment later.

**Comment by casperklein** [comment]
> https://github.com/docker-mailserver/docker-mailserver/pull/2882#issuecomment-1358436858

Next week 👍

**Comment by georglauterbach** [comment]
> https://github.com/docker-mailserver/docker-mailserver/pull/2882#issuecomment-1358436858
> 
> 
> 
> Next week 👍 

👍🏼

Can we in the meantime merge #2901 and #2902?

**Comment by casperklein** [comment]
#2901 yes
#2902 I will look into this also next week

**Review by casperklein — APPROVED** [review]

**Pull request merged**
