### PR TITLE
setup.sh color variables added

### PR DESCRIPTION
**Pull request by casperklein**
# Description

To make the source more readable, color variables have been added.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the documentation)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
@aendeavor There are two escape sequences in use. See `$RESET` and `$RESET2`. I think it's safe to only use `$RESET2`. Can you confirm that? In my test, I did not notice any difference.

**Comment by wernerfred** [comment]
Just Reading this on my mobile but didnt we Had Something similar from @aendeavor which was reverted then as colorized Output Breaks with current bats?
Ist this resolved now? Didnt have the PR # in my Kind nur there was a discussion about that already. 
I will See If i can find it again later

**Comment by aendeavor** [comment]
> @aendeavor There are two escape sequences in use. See `$RESET` and `$RESET2`. I think it's safe to only use `$RESET2`. Can you confirm that? In my test, I did not notice any difference.

Yes, it's safe to use `\e[0m` only. This sequence removes _all_ applied attributes, which is desired.

`\e[39m` sets the Color to the default value again - this is why there is no difference here, as we're just working with colours.

**Comment by aendeavor** [comment]
> Just Reading this on my mobile but didnt we Had Something similar from @aendeavor which was reverted then as colorized Output Breaks with current bats?

Not quite the same. In our case, the problem was supervisord not handling the escape sequences properly. As a result, the bats were not able to handle the output.

> Ist this resolved now? Didnt have the PR # in my Kind nur there was a discussion about that already. 

Supervisor can still not handle color... which makes me angry.

**Review by aendeavor — APPROVED** [review]

**Comment by aendeavor** [comment]
Very nice. From my PoV, this can be merged:)

**Pull request merged**
