### PR TITLE
Fix delmailuser error handling

### PR DESCRIPTION
**Pull request by casperklein**
# Description

Discussed [here](https://github.com/docker-mailserver/docker-mailserver/pull/2172#discussion_r703662165)

This PR fixes conditions, that never worked?!

```sh
    if ! sed -i "/^${EMAIL}|/d" "${DATABASE}"
    then
      echo "${UNESCAPED_EMAIL} couldn't be deleted in ${DATABASE}." >&2
      ERROR=true
    fi
```

The error message above is only triggered, if something fundamental went wrong (e.g. DB doesn't exist at all).
It will not trigger, if `$EMAIL` doesn't exist.

To-do: Update other scripts in `target/bin`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by polarathene — DISMISSED** [review]

**Review by georglauterbach — APPROVED** [review]

**Review by polarathene — APPROVED** [review]

**Comment by polarathene** [comment]
> There may be aliases in that file or not. If not, then there is nothing to delete. Got it?

Oh, hopefully I haven't suggested it in previous reviews incorrectly then :grimacing: 

~~Perhaps `sedfile` should be renamed `sed-err-without-change`? (or something more terse).~~

**EDIT:** I see that it's intent is described at the top of the file, I just had to locate it:

https://github.com/docker-mailserver/docker-mailserver/blob/c7e498194546416fb7231cb03254e77e085d18df/target/bin/sedfile#L3

**Review by polarathene — APPROVED** [review]
Might as well convert the `sed`/`sedfile` delimiter `/` to `|`? Or are we not wanting to be strict on that consistency?

**Review by georglauterbach — APPROVED** [review]
I agree with @polarathene, would also like to see the delimiter changed :)

**Comment by casperklein** [comment]
I am wondering if `|` as default  substitution delimiter is a good practice:

The line

`      -e "/ ${EMAIL}$/d" -e "s/,${EMAIL}//g" -e "s/${EMAIL},//g" \`

would become

`      -e "/ ${EMAIL}$/d" -e "s|,${EMAIL}||g" -e "s|${EMAIL},||g" \`

Am I the only one, that finds it odd, to use different delimiter for different operations? The delete statement does not accept the `|` delimiter.
I am fine with using it, when necessary (especially when replacing paths to avoid endless escaping). In the other cases I like to stick to "global" defaults almost all dev/examples use.

**Comment by casperklein** [comment]
PS: I am fan of small (one topic) PRs. My goal was just to introduce `sedfile`. If we want a new substation delimiter across DMS, then there should be a "one PR to fix them all 😄"

While we are here and this is a small/clear PR, I agree, it doesn't hurt to fix that also.

At the moment, I think it's 50:50 across the code base where we use `/` and `|`. See my comment above, if we should continue either with `/` or `|`.

**Comment by NorseGaud** [comment]
> I am wondering if `|` as default  substitution delimiter is a good practice:
> 
> 
> 
> The line
> 
> 
> 
> `      -e "/ ${EMAIL}$/d" -e "s/,${EMAIL}//g" -e "s/${EMAIL},//g" \`
> 
> 
> 
> would become
> 
> 
> 
> `      -e "/ ${EMAIL}$/d" -e "s|,${EMAIL}||g" -e "s|${EMAIL},||g" \`
> 
> 
> 
> Am I the only one, that finds it odd, to use different delimiter for different operations? The delete statement does not accept the `|` delimiter.
> 
> I am fine with using it, when necessary (especially when replacing paths to avoid endless escaping). In the other cases I like to stick to "global" defaults almost all dev/examples use.

I think it's odd and also entirely unnecessary.

**Comment by NorseGaud** [comment]
> PS: I am fan of small (one topic) PRs. My goal was just to introduce `sedfile`. If we want a new substation delimiter across DMS, then there should be a "one PR to fix them all 😄"
> 
> 
> 
> While we are here and this is a small/clear PR, I agree, it doesn't hurt to fix that also.
> 
> 
> 
> At the moment, I think it's 50:50 across the code base where we use `/` and `|`. See my comment above, if we should continue either with `/` or `|` or as a third option: decide from case to case which fits better.

A PR should have one purpose and limited changes so that we know what is absolutely necessary, maybe two if it's related. Otherwise, we should have a PR to support a new style change and do it all at once. 

I'm guilt of trying to push a bunch of stuff in one PR but recently have stopped doing it. Imagine we make a small change that's unrelated in this PR and then later add logic that depends on that change. We then have to for some reason revert this PR and it causes a new problem that is now unrelated. This makes this really complicated and harder to maintain.

**Comment by polarathene** [comment]
> If we want a new substation delimiter across DMS, then there should be a "one PR to fix them all "

I started to use `|` since [it was decided back in Feb](https://github.com/docker-mailserver/docker-mailserver/pull/1801#discussion_r579870882) due to encountering quite a bit of variation back then. If you want to go with a mix of `/` and `|`(when URIs are involved), that's fine by me too.

I did a "one PR to fix them all", at least in the [scope of `start-mailserver.sh` back then](https://github.com/docker-mailserver/docker-mailserver/pull/1823/files) :stuck_out_tongue:

**Comment by georglauterbach** [comment]
This can be merged as the tests do not pass because of the setup-log-problem.

**Comment by georglauterbach** [comment]
I will leave this in the `v10.2.0` if you thin this can be merged soon.

**Comment by casperklein** [comment]
> I will leave this in the v10.2.0 if you thin this can be merged soon.

I haven't merged it yet, to give enough time for others to review if they want. From my side, this can be merged at any time 👍

**Comment by georglauterbach** [comment]
@NorseGaud is there anything with this PR you'd like to see changed? If not, feel free to merge it :D

**Review by wernerfred — APPROVED** [review]

**Review by NorseGaud — APPROVED** [review]
I'll let Casper handle merging :)

**Pull request merged**
