### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wolkenschieber**
Corrected _Customizing IMAP Folders_ link

# Description

This pull request fixes a typo in the _Customizing IMAP Folders_ link.

## Type of change

- [x] Readme update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
Good finding, thank you. I think that was a typo while creating the directory structure. Instead of adjusting the link, we should rename the `uses-cases` directory to `use-cases`.

@polarathene @wernerfred Whats your take on this?

**Comment by wernerfred** [comment]
> @polarathene @wernerfred Whats your take on this?

This:

> Instead of adjusting the link, we should rename the `uses-cases` directory to `use-cases`.

**Comment by casperklein** [comment]
@wernerfred Do you know of an easy way to check for dead internal links in our documentation?

**Comment by wernerfred** [comment]
> @wernerfred Do you know of an easy way to check for dead internal links in our documentation?

sadly not, i think @polarathene mentioned that he wanted to build something like this for CI last year but had no time to implement it yet IIRC

**Comment by polarathene** [comment]
> Do you know of an easy way to check for dead internal links in our documentation?

Yes it's on my backlog, my broken PC disk should have notes regarding it once I restore it later this week.

I think I was going to use a rust project `lychee` with the CI. We need to test markdown local links are valid (building docs with `--strict` mostly does that at least for file paths, but fails against validating anchor tags `#`), and also testing links on built docs.

Anyway, it'll get addressed eventually unless someone beats me to it :sweat_smile:

**Comment by polarathene** [comment]
Also agree on changing the docs file name instead.

It won't affect previous docs which are versioned (_which also retain typos/bugs_). We may at a later point want to consider rebuilding old tags with newer version of the docs generator, but it may not be worth it either (_there was some deprecations a while back, one with admonition support I think and recently the mermaid one)_.

**Review by casperklein — DISMISSED** [review]

**Review by polarathene — APPROVED** [review]

**Review by wernerfred — APPROVED** [review]

**Review by georglauterbach — APPROVED** [review]

**Comment by georglauterbach** [comment]
I will merge this after #2420

**Pull request merged**
