### PR TITLE
chore(Makefile): Ensure targets are always run

### PR DESCRIPTION
**Pull request by polarathene**
# Description

This commit is pulled out of https://github.com/docker-mailserver/docker-mailserver/pull/3012 and is [explained in this PR comment](https://github.com/docker-mailserver/docker-mailserver/pull/2857#discussion_r1013767738):

> it is **not** defined as a target like `ALWAYS_RUN:`, but just as `.PHONY: ALWAYS_RUN` :) This suffices to tell `make` to always run the target.

`.PHONY: ALWAYS_RUN` already exists in the Makefile. This PR just applies it more broadly as decided by @georglauterbach 

---

**NOTE:** From what I have seen in [Makefile docs for `.PHONY`](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) this seems a bit of a different approach?

The targets seem to get appended to the `.PHONY:` target, rather than this usage of prefixing target values with `ALWAYS_RUN`? (_a target dependency that is `.PHONY`_) It seems like it may behave the same way, so perhaps it doesn't matter?

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

### CODE REVIEW

**Review by georglauterbach — APPROVED** [review]

**Comment by georglauterbach** [comment]
> **NOTE:** From what I have seen in [Makefile docs for `.PHONY`](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) this seems a bit of a different approach?
> 
> The targets seem to get appended to the `.PHONY:` target, rather than this usage of prefixing target values with `ALWAYS_RUN`? (_a target dependency that is `.PHONY`_) It seems like it may behave the same way, so perhaps it doesn't matter?

I guess both work, I have seen both too.

**Review by casperklein — APPROVED** [review]
BTW: Even when `.PHONY: ALWAYS_RUN` and all other "ALWAYS_RUN" are removed, the function keeps the same. All targets are always run.

**Comment by georglauterbach** [comment]
> BTW: Even when `.PHONY: ALWAYS_RUN` and all other "ALWAYS_RUN" are removed, the function keeps the same. All targets are always run.
> 
> At least I couldn't identify any difference.

I thought exactly the same, and had already removed it at some point in time. But then, `make` told me the recipe was already up to date - very confusing! I don't reall know why, but this way, we're on the safe side.

As an alternative to `make`, I'd go with [`just`](https://github.com/casey/just), a proper command runner (remember: `make` is a build system!). But since everyone has `make`, I guess the transition would result in a bad development experience..

**Comment by polarathene** [comment]
> As an alternative to `make`, I'd go with [`just`](https://github.com/casey/just), a proper command runner (remember: `make` is a build system!). But since everyone has `make`, I guess the transition would result in a bad development experience..

I'm not opposed to it changing from `make` in a future release. Most development using it is by us regular maintainers, and I'm not sure if it offers much value for anyone else not contributing?

[Earthly](https://earthly.dev/) has been on my radar, but I think that'd be more invasive of a change, and I'm not sure how beneficial it'd be as I think it may not support some features we're using with `buildx` (_plus that's what our CI is setup with, switching would need to be worthwhile_ :sweat_smile: ). `just` looks pretty nice, plus it's in rust which is a win for me :stuck_out_tongue:

**Comment by georglauterbach** [comment]
> I'd be open towards changing from `make` in a future release too. Most development using it is by us regular maintainers, and I'm not sure if it offers much value for anyone else not contributing?

You're probably right. @casperklein what's your take on this?

> [Earthly](https://earthly.dev/) has been on my radar, but I think that'd be more invasive of a change, and I'm not sure how beneficial it'd be as I think it may not support some features we're using with `buildx` (_plus that's what our CI is setup with, switching would need to be worthwhile_ :sweat_smile: ). `just` looks pretty nice, plus it's in rust which is a win for me :stuck_out_tongue: 

I've never used earthly, I will have a look at it :) Just is something I use on a daily basis, and it works very well. I discovered it because I live Rust too 🙈

**Comment by casperklein** [comment]
Pro `make`: well known and wide spread. And sufficient for our usage?
Pro something else: Could make things easier/more efficient.

Switching to something else should bring useful benefits. Otherwise I don't think it's worth to convert to something else. Also it's not that often, that our Makefile is modified. It's there and it does it's job.
But personally I don't care, if I have to run `make`, `just` or something else in the future 👍

**Comment by polarathene** [comment]
> Switching to something else should bring useful benefits. Otherwise I don't think it's worth to convert to something else.

Personally the Makefile has not been a fun experience for me with it's syntax and gotchas. So I think the benefit is improved maintenance with `just` (_supposedly, I haven't looked into it much myself_). That tends to be a good thing for new maintainers too if it would be cryptic to them :sweat_smile: (_some parts aren't particularly google friendly, so a lot of sifting through `git blame` to grok what is going on_)

> Also it's not that often, that our Makefile is modified. It's there and it does it's job.

Fair. It's been stripped down quite a bit since it's first usage, but the syntax + usage perhaps more complicated to grok.

It's at least easy to use and does work well for what we need. Only a small file that shouldn't need much more maintenance going forward, so I agree there's no major reason to switch away, but I'm open to it :+1:

**Comment by georglauterbach** [comment]
I started a side-by-side comparison of the `Makefile` & the corresponding `Justfile` from `just`. Although `just` is _way_ nicer, it occured to me that we would need this in our CI as well. This is inconvenient! I'd rather invest work in keeping the `Makefile` clean and short, even though I love just (I use it on a daily basis).

**Pull request merged**
