### PR TITLE
scripts: housekeeping & cleanup setup (2/2)

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

(First) Follow up of #3115. Sibling of #3121. **This is mostly a cleanup & housekeeping PR**; changes are partially split from #3112 to make reviewing easier.

Commits are cleanly separated; reviewing commit-by-commit is advised.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by polarathene — DISMISSED** [review]
> Commits are cleanly separated; reviewing commit-by-commit is advised.

Really nice review diffs this time, quick and easy :grin: :tada:

**Review by casperklein — DISMISSED** [review]

**Comment by casperklein** [comment]
BTW: do we really need a separate fix stack? We could move those fixes into the corresponding setup functions.

**Comment by georglauterbach** [comment]
> BTW: do we really need a separate fix stack? We could move those fixes into the corresponding setup functions.

#3121 removed the stick entirely 😉

**Comment by georglauterbach** [comment]
I will resolve conflicts tomorrow :)

**Pull request merged**
