### PR TITLE
release: v12.0.0

### LINKED ISSUE #2952: [BUG] v11.3.1 was published with update check against the wrong version (v11.3.0)
### What happened and when does this occur?

`/VERSION` contains `11.3.0` in the image with the `:11.3.1` tag.

### What did you expect to happen?

`/VERSION` to contain `11.3.1`

### How do we replicate the issue?

```bash
# Outputs: `11.3.0`
docker run -it --rm --entrypoint cat mailserver/docker-mailserver:11.3.1 VERSION
```

### DMS version

11.3.1

### Improvements to this form?

My bug report can be summarized in 2 lines. The bug is OS agnostic and doesn't even require any service to be ran. This whole form is nonsense for this particular case. You should allow to bypass it.

### LINKED ISSUE #3098: [BUG] ClamAV security vulnerability
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

ClamAV

### What happened and when does this occur?

See: https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html

### What did you expect to happen?

We should update our debian base image

### How do we replicate the issue?

1.
2.
3.
...

### DMS version

latest

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

_No response_

### Relevant log output

_No response_

### Other relevant information

https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_

### LINKED ISSUE #3202: [BUG] fail2ban eats all CPUs and does not respond in setup.sh
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

fail2ban and setup.sh

### What happened and when does this occur?

In the current state of my deployment, fail2ban eats all of the host's CPUs constantly when I enable it. If I disable it and restart the container, CPU load is around 2% on the machine. When it's enabled, it's at a steady 100%. There are also a good 30 fail2ban processes running in parallel.

I believe this occurred after I manually banned some IPs using setup.sh. Previously to banning them, fail2ban wasn't very effective (I also am facing #3178) but at least it didn't eat all CPU.

Sadly, I can't even try to rollback my changes, because now setup.sh is unable to unban these IPs (the output is: `[  ERROR  ]  Fail2ban not running [  ERROR  ]  Aborting` I suppose because it can't reach the fail2ban socket due to the high CPU load.)

### What did you expect to happen?

I expected:
-  fail2ban not to take all of the machine's CPU
-  setup.sh to be able to unban the IPs I banned

### How do we replicate the issue?

I'm really unsure if this can be reproduced, but here what I did:

1. Use setup.sh to ban around 8 IP addresses from the same subnet
2. Restart container

### DMS version

v11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

ArchLinux

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: mydomain.com
    env_file: mailserver.env
    environment:
      - VIRTUAL_HOST=mail.mydomain.com
      - LETSENCRYPT_HOST=mail.mydomain.com
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"  # POP3
      - "995:995"  # POP3 (with TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ../../reverse_proxy/docker-data/nginx-proxy/certs/:/etc/letsencrypt/live/:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

_No response_

### Other relevant information

_No response_

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [x] I am rather experienced with docker
- [x] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [x] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

This PR marks the feature freeze phase for the `v12.0.0` release.

The current `:edge` image will be tested for roughly **10 days** and if no bugs get reported, `v12.0.0` will be released. During this testing period, only PRs that do not change functionality will be merged.

**If you want to support us, give the latest `:edge` image a try and report any issues you encounter back to this PR.**

Documentation updates may be merged. **Feature freeze is in place until 9 April 2023**.

Closes #2952
Closes #3098
Closes #3202

## Type of change

- [x] Release

## Release-Checklist:

- [x] Update CHANGELOG.md
- [x] Update version in VERSION
- [x] Draft release

### CODE REVIEW

**Comment by polarathene** [comment]
> Please add your contributions to `CHANGELOG.md` as well :)

I'll try sort mine out in the next few days.

**Comment by georglauterbach** [comment]
> > Please add your contributions to `CHANGELOG.md` as well :)
> 
> 
> 
> I'll try sort mine out in the next few days.

No rush :) I'd start with the freeze after the Postsrsd issue is resolved. I'll be unavailable 11. - 26.; if you want to release v12.0.0 in the meantime, go ahead, if not, we can do a longer freeze and I will release it when I'm back from vacation.

**Comment by polarathene** [comment]
@casperklein any of your PRs that you want to add to this changelog?

I'll still need to setup a PR for Dovecot and PostSRSd disabling chroot, then good for release.

Probably want to [address the `SA_KILL` change properly](https://github.com/docker-mailserver/docker-mailserver/pull/3058#issuecomment-1444838506) too though.

**Comment by georglauterbach** [comment]
@polarathene when do you think the PR for the Dovecot/PostSRSd-chroot-change will drop?

**Comment by georglauterbach** [comment]
> I haven't been able to tackle it yet, way behind and burning out sweat_smile
> 
> Ideally I can find some time this weekend to look into it. PostSRSd should just be adjusting the config file, not sure about Dovecot yet, but there's a Discussion that shared what worked for them and might be all that needs to be done.

Just tell me, I can try to tackle this as well and relieve you from some of the weight ❤️

Maybe @jrpear can help us here as well if he's interested in starting to really work with config/Bash code in DMS :)

**Comment by polarathene** [comment]
> Just tell me, I can try to tackle this as well and relieve you from some of the weight

Much appreciated! :heart: :pray: 

- [Tracking issue to close](https://github.com/docker-mailserver/docker-mailserver/issues/3174).
- [Dovecot config hint](https://github.com/orgs/docker-mailserver/discussions/3172#discussioncomment-5276395) (supposedly that's all that needs to be done).
- PostSRSd should just need this line commented out IIRC, default should be no chroot:

   https://github.com/docker-mailserver/docker-mailserver/blob/1c231053d0a6efe93cb02112142719c5adc567af/target/postsrsd/postsrsd#L41

   [More info you can reference for postsrsd config handling](https://github.com/docker-mailserver/docker-mailserver/pull/3160#issuecomment-1465326589).

**Comment by georglauterbach** [comment]
Feature freeze is now in place! It lasts 10 days (because v12.0.0 is really big).

I will draft a release on GitHub later.

**Comment by casperklein** [comment]
I think it's fine to [deprecate](https://github.com/docker-mailserver/docker-mailserver/pull/2851#issuecomment-1287889571) the `ONE_DIR ` ENV with this release?

**Comment by polarathene** [comment]
> I think it's fine to [deprecate](https://github.com/docker-mailserver/docker-mailserver/pull/2851#issuecomment-1287889571) the `ONE_DIR ` ENV with this release?

Yeah, sounds good. It's effectively only relevant to `mail_state.sh` now and from v12 only really cares about [`/var/mail-state` being present to toggle the behaviour](https://github.com/docker-mailserver/docker-mailserver/blob/adb38207ad35101bb01ce21621baa1c342fa205d/target/scripts/startup/setup.d/mail_state.sh#L11).

**Comment by georglauterbach** [comment]
Let's please do this with v13.0.0; which should not take too long actually.

Today is the end of the freeze. I don't know what your deprecation would look like, but for `ONE_DIR=0`, an addition to `_environment_variables-bavkwards_compatibility` is required - which would make the freeze useless.

I don't mind skipping v12.1.0 and going to v13.0.0 immediate, but please let's not push this in here as well.

v13.0.0 will focus on some ENV changes already, it's more fitting therefore to go into v13.0.0.

**Comment by georglauterbach** [comment]
Please provide your approval if you think this is fine :) Happy Easter!

**Review by polarathene — APPROVED** [review]

**Comment by casperklein** [comment]
Just to be clear, I didn't plan to do any code changes or something. Just mention it in the changelog, that `ONE_DIR=0` is marked deprecated and will be removed in the future (v14 or later). Just to inform people early.
I am fine with handling this later.

**Review by casperklein — APPROVED** [review]

**Comment by georglauterbach** [comment]
> Just to be clear, I didn't plan to do any code changes or something. Just mention it in the changelog, that `ONE_DIR=0` is marked deprecated and will be removed in the future (v14 or later). Just to inform people early.
> 
> I am fine with handling this later.

👍🏼 I think we should be as thorough as possible and add a bit of code for the `=0` case, hence my proposal.

I will make sure to include this in v13.0.0.

---

This PR is ready to be merged now. I will take care of the release :)

**Pull request merged**
