### PR TITLE
fix: Update `dovecot-fts-xapian` to `1.7.13`

### PR DESCRIPTION
**Pull request by polarathene**
# Description

[Reported](https://github.com/docker-mailserver/docker-mailserver/issues/4052#issuecomment-2197237232) with [cause identified as a regression](https://github.com/docker-mailserver/docker-mailserver/issues/4052#issuecomment-2203935503) upstream.

Upstream doesn't seem to maintain a changelog and the release just states "bug fixes", [`1.7.13` was released in May 2024](https://github.com/grosjo/fts-xapian/issues/163#issuecomment-2201553781).

Updating to this release contains a fix to a regression that introduced a bug with indexing.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

**Review by casperklein — APPROVED** [review]

**Review by georglauterbach — APPROVED** [review]

**Review by casperklein — APPROVED** [review]

**Comment by georglauterbach** [comment]
Build seems to be failing; can you investigate @polarathene?

**Comment by casperklein** [comment]
> Build seems to be failing; can you investigate @polarathene?

Should be fixed, see my last commit.

**Comment by polarathene** [comment]
Yeah I just noticed the failure myself and was going to comment on why we have this handled in the `Dockerfile` instead of a related script method?

https://github.com/docker-mailserver/docker-mailserver/blob/b3a5e9e4e8eb0de311940c86d233c66fa3d72354/Dockerfile#L85-L86

**Review by georglauterbach — APPROVED** [review]

**Comment by casperklein** [comment]
> why we have this handled in the `Dockerfile` instead of a related script method?
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/b3a5e9e4e8eb0de311940c86d233c66fa3d72354/Dockerfile#L85-L86

I guess it was done, to not have the build deps in the final image.

**Comment by polarathene** [comment]
> I guess it was done, to not have the build deps in the final image.

I meant keep the version specific parts in a helper function instead of via `RUN`. But I guess since we already have run `build.sh` before `compile.sh` neither is really suitable for it?

Could perhaps avoid having the version in the `.deb` filename, but I'm not 100% sure how that affects the layer caching, it should be invalidated with the COPY directive right?

**Comment by casperklein** [comment]
> I meant keep the version specific parts in a helper function instead of via RUN

That is "fixed" now.

>  it should be invalidated with the COPY directive right?

Idk 🤷

**Pull request merged**
