### PR TITLE
Updated docker-compose.yml's ports and volumes section

### LINKED ISSUE #1903: [BUG] Postfix acts as open relay by default when deploying a stack in docker swarm mode
# Bug Report

## Context

When the recommended docker-compose.yml gets deployed into docker swarm mode, all ports get published through the ingress network by default which makes all incoming connections look like they come from within `10.0.0.0/24` which is in `mynetworks`.

### What is affected by this bug?

Postfix

### When does this occur?

When docker-mailserver is deployed as a stack or service in docker swarm mode without explicitly setting the port publish mode to host.

### How do we replicate the issue?

1. Configure docker-mailserver as described in the documentation
2. Deploy with `docker stack deploy` instead of `docker-compose up`.
3. Connect with `telnet`/`netcat` or wait for the usual spam to arrive.

### Actual Behavior

**telnet:**
```smtp
220 mail.mydomain.de ESMTP
HELO mydomain.de
250 mail.mydomain.de
MAIL FROM: <test@example.com>
250 2.1.0 Ok
RCPT TO: <test@gmail.com>
250 2.1.5 Ok
```

**log:**
```
Apr 13 18:37:05 77daf529c864 postfix/postscreen[2129]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=0 dropped=0 entries
Apr 13 18:37:05 77daf529c864 postfix/postscreen[2129]: CONNECT from [10.0.0.2]:60456 to [10.0.0.8]:25
Apr 13 18:37:05 77daf529c864 postfix/postscreen[2129]: WHITELISTED [10.0.0.2]:60456
Apr 13 18:37:05 77daf529c864 postfix/smtpd[2130]: connect from unknown[10.0.0.2]
Apr 13 18:37:05 77daf529c864 opendmarc[1135]: ignoring connection from [10.0.0.2]
Apr 13 18:38:15 77daf529c864 postfix/smtpd[2130]: 453B6201E96: client=unknown[10.0.0.2]
```

### Expected Behavior

**telnet:**
```smtp
220-mail.mydomain.de ESMTP
HELO mydomain.de
250 mail.mydomain.de
MAIL FROM: <test@example.com>
250 2.1.0 Ok
RCPT TO: <test@gmail.com>
550 5.5.1 Protocol error
```

**log:**
```
Apr 13 18:42:41 62de164fa2ea postfix/postscreen[1877]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=0 dropped=0 entries
Apr 13 18:42:41 62de164fa2ea postfix/postscreen[1877]: CONNECT from [x.x.52.104]:33428 to [172.18.0.14]:25
Apr 13 18:42:41 62de164fa2ea postfix/dnsblog[1881]: warning: dnsblog_query: lookup error for DNS query 104.52.x.x.list.dnswl.org: Host or domain name not found. Name service error for name=104.52.x.x.list.dnswl.org type=A: Host not found, try again
Apr 13 18:42:41 62de164fa2ea postfix/dnsblog[1881]: warning: dnsblog_query: lookup error for DNS query 104.52.x.x.zen.spamhaus.org: Host or domain name not found. Name service error for name=104.52.x.x.zen.spamhaus.org type=A: Host not found, try again
Apr 13 18:42:45 62de164fa2ea postfix/postscreen[1877]: PREGREET 17 after 3.8 from [x.x.52.104]:33428: HELO mydomain.de
Apr 13 18:43:08 62de164fa2ea postfix/postscreen[1877]: NOQUEUE: reject: RCPT from [x.x.52.104]:33428: 550 5.5.1 Protocol error; from=<test@example.com>, to=<test@gmail.com>, proto=SMTP, helo=<mydomain.de>
```

## How this should be fixed

To be fair, there's probably no catch-all solution to this. But there should at least be a warning in the documentation since this leads to instances of docker-mailserver to become unsecured spam relays. In the 15 minutes I needed to notice and fix this, I got a total of 9 abuse reports from my datacenter.

Possible solutions:
* Remove `10.0.0.0/24` from `mynetworks` when running in swarm mode. Direct linking of containers is deprecated, so other containers will probably contact the mail server through a different overlay network (subnet `10.0.11.0/24` in my case) anyway.
* Define ports in long format and mark them as `mode: host`. This would be prefered so the server can see the actual IP address but might not be possible in multi-node swarms.
  ```yaml
  ports:
  - target: 25
    published: 25
    protocol: tcp
    mode: host
  ```

### PR DESCRIPTION
**Pull request by aendeavor**
# Description

Makes the `ports` and `volumes` sections more readable and suited for Swarm as well.

Fixes #1903

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the documentation)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
LGTM 👍  However, some questions came up:

- Do we official support Swarm? For non swarm users, this adds additional lines, that makes it maybe complicated/confusing for new users. I haven't seen this syntax often in the wild. Maybe a separate compose file for swarm could achieve the same?
- Does this port syntax not need quotes to avoid the "base60 problem"

**Comment by aendeavor** [comment]
>  Do we official support Swarm?

We don't officially support Swarm. 

> For non swarm users, this adds additional lines, that makes it maybe complicated/confusing for new users.

I think this project is not suited for new users at all... :D

>  Does this port syntax not need quotes to avoid the "base60 problem"

I'm running this myself and I'm not having problems.

**Comment by casperklein** [comment]
"New" users in relation to this project, not general newbies 😉 

If Swarm is not supported, then I would not over-complicate the default configuration (adding three not necessary lines per port mapping + as said, not many projects use this syntax for non swarm setups.) and move this to `docker-compose-swarm.yml`? But I don't want to be the judge here. I'll leave it to you or someone else, I've added my cents 😆

**Review by casperklein — APPROVED** [review]

**Comment by aendeavor** [comment]
I actually like this notation as it makes clear how and which ports exactly are exposed and the same goes for volumes. I also believe this does not add "unneeded complexity", actually, I think it removes complexity as things are clearer.

As for #1903, this PR makes certain (actually unsupported, but nevertheless relevant) setups more secure. As I said, we don't support Swarm, but this does not change the fact that many people use it :D

I have revert the volumes section, and minified the ports section. I think this is a good compromise. Do you agree?

**Comment by casperklein** [comment]
One last thing: Do you think it's worth to add POP3(s) Ports also, for completeness of the examples?

**Comment by wernerfred** [comment]
I'm against this for the same reason @casperklein mentioned:
> For non swarm users, this adds additional lines, that makes it maybe complicated/confusing for new users.

I personally find it hard to read and to fit it in a docker-compose setup I would need to rewrite it to have it in a "well-known" style (although it does not change functionality).

As you said we do not officially support docker swarm, therefore imho this config example would better fit in the documentation instead of toplevel docker-compose

**Comment by dfyx** [comment]
As the person who submitted the original issue, I'd be fine with this going in the use cases directory but I'd highly recommend adding a line like the following to the readme:

> **Warning!** If you plan on using this with docker swarm mode, please read [this use case](#) as there are security concerns with port mappings.

**Comment by aendeavor** [comment]
Alright, I was overruled. @dfyx could you  provide a PR in the docs for this and a link in the README?

**Comment by dfyx** [comment]
No promises that I'll get it done today but I'll try to do it as soon as possible.

**Pull request closed without merging**
