### PR TITLE
ci: add dedicated feature requests to new project automatically

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

This change saves me a few clicks for all new dedicated feature request issues.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code

### CODE REVIEW

**Review by polarathene — APPROVED** [review]
I haven't used "projects" myself, not too familiar with the difference in relevance to labels and milestones.

What's the exact value add for you here? I don't think I've seen you use it in the past, we just left feature requests open (_optionally closing if stale_).

Is there additional projects anticipated beyond a backlog for "DMS Core"?

**Comment by georglauterbach** [comment]
> I haven't used "projects" myself, not too familiar with the difference in relevance to labels and milestones.
> 
> What's the exact value add for you here? I don't think I've seen you use it in the past, we just left feature requests open (_optionally closing if stale_).
> 
> Is there additional projects anticipated beyond a backlog for "DMS Core"?

I've come to very much enjoy Kanban boards at work, and I'd like to have this experience here as well. These boards provide a good overview of the current state. I think they supplement the existing labels and milestones quite nicely. While I cannot think of any other projects at this time, we never know.

The project also provides insights into whether somethat is currently handled, or whether is has maybe not been accepted yet? I like that.

**Comment by polarathene** [comment]
> I've come to very much enjoy Kanban boards at work, and I'd like to have [this experience](https://github.com/orgs/docker-mailserver/projects/4) here as well. These boards provide a good overview of the current state.

Oh yeah, I haven't seen kanban boards for a while, but they're great! I didn't know Github supported that, awesome 😎 

Is there somewhere else in the Web UI to easily navigate to that? Or should we have a link on the README?

> The project also provides insights into whether something is currently handled, or whether it has maybe not been accepted yet? I like that.

Yes, I'm aware of that value and fully onboard with it compared to glancing over the issues/pr page to gauge status of what's being worked on and such.

**Comment by georglauterbach** [comment]
On the right side of issues and PRs, you have the information about who participates and so on:

image

In the "Projects" section, just press on the name of the project "DMS Features" and you will directly get to the Kanban board.

**Pull request merged**
