### PR TITLE
release: v11.3.0

### PR DESCRIPTION
**Pull request by casperklein**
# Description

This PR marks the feature freeze phase for the `v11.3.0` release.

The current `:edge` image will be tested for roughly one week and if no bugs get reported, `v11.3.0` will be released. During this testing period, only PRs that do not change functionality will be merged.

**If you want to support us, give the latest `:edge` image a try and report any issues you encounter back to this PR.**

Documentation updates may be merged. **Feature freeze is in place until 18 Dec 2022**.

## Type of change

- [x] Release

## Release-Checklist:

- [x] Update CHANGELOG.md
- [x] Update version in VERSION
- [x] Draft release

### CODE REVIEW

**Review by georglauterbach — DISMISSED** [review]
Running the latest `:edge` now for a prolonged period, seems good to me.

**Comment by georglauterbach** [comment]
Alright, let's finish this up @docker-mailserver/maintainers

**Comment by casperklein** [comment]
No general issues in my setup. However, building with dovecot community repo [is broken for some days now](https://github.com/docker-mailserver/docker-mailserver/issues/2935). I am going to provide a fix tonight/tomorrow.

**Comment by polarathene** [comment]
A PR was accidentally merged early by me and should be reverted.

---

Did we want to include in the ChangeLog and release notes the pinned deprecation notices?:

- https://github.com/docker-mailserver/docker-mailserver/issues/2642
- https://github.com/docker-mailserver/docker-mailserver/issues/2679

**Comment by georglauterbach** [comment]
@polarathene please add the notice to the Changelog. We can then merge this.

**Comment by polarathene** [comment]
- Updated the draft release and this PR changelog to include the deprecation notices :+1: 
- Rebased this PR onto current master.

**Review by polarathene — APPROVED** [review]

**Comment by georglauterbach** [comment]
> Is https://github.com/docker-mailserver/docker-mailserver/pull/2937 also getting squeezed into 11.3?

No, this would be too big of a change :) I will go ahead and release v11.3 now.

**Review by georglauterbach — APPROVED** [review]

**Comment by casperklein** [comment]
> > Is #2937 also getting squeezed into 11.3?
> 
> No, this would be too big of a change :) I will go ahead and release v11.3 now.

Big change? This is a small fix for a currently broken build. IMO this should have been merged before, that's why I labeled it accordingly.

Now a version was released, that cannot be build with the dovecot community repo enabled. That makes it hard(er) to test, before making it the default in the next version..

**Comment by georglauterbach** [comment]
> Big change? This is a small fix for a currently broken build. IMO this should have been merged before, that's why I labeled it accordingly.

A no-issue IMO because a _custom_ build is broken, not the one used to build v11.3. Now, you cannot build the custom image on the v11.3 tag, I see and I agree, not nice. But also not a dealbreaker. If we had chosen to merge this, I would have requested another feature freeze.

So, my proposal: why don't we just release a patch for this? For example v11.3.1? I can revert the Fail2Ban PR if wo choose to go this route.

> Now a version was released, that cannot be build with the dovecot community repo enabled. That makes it hard(er) to test, before making it the default in the next version..

Should not affect testing as we have enough tests running (through PRs) before we release v12.

**Comment by casperklein** [comment]
> If we had chosen to merge this, I would have requested another feature freeze.

In that special case, I don't think that should be necessary, as it only fixed the building (with dovecot repo), not running DMS. But even if we did so, what's wrong with that? We don't have any urge to release a new version 🤷 

> I can revert the Fail2Ban PR 

Yes please. I haven't time yet to test and finally approve it. My personal deadline for this is mid January, but hopefully earlier.

My proposal: Releasing `11.3.1` with the following changes:

- #2937 
- Removal of #2903

**Comment by georglauterbach** [comment]
@casperklein you can now merge #2937 (I cannot update the branch ref since it is in your repository, not DMS; hence, I cannot merge). Please also prepare the PR for the release. No feature freeze required this time.

**Comment by georglauterbach** [comment]
> > If we had chosen to merge this, I would have requested another feature freeze.
> 
> In that special case, I don't think that should be necessary, as it only fixed the building (with dovecot repo), not running DMS. But even if we did so, what's wrong with that? We don't have any urge to release a new version shrug

I wanted to have this done so I can use the latest edge with the new F2B. So, no, there is no urge, but there is also no reason to prolong the time span unnecessarily.

**Pull request merged**
