### PR TITLE
Postfix: rename "smtps" to "submissions"

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

@polarathene I am unsure whether we need to change even more. Please tell me if I forgot about something crucial.

## Type of change

- [x] Update (non-breaking change that does improve existing functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by polarathene** [comment]
> Please tell me if I forgot about something crucial.

Nope, just replacing `smtps` for `submissions` in the project files should do it AFAIK.

We may want to add a minor test that greps 465  in `/etc/services` of the container to confirm it is assigned `submissions`. If the base image changes, that sometimes won't be the case (surprisingly with Fedora), so it'd be good to catch that instead of potential confusion troubleshooting it down to that issue :sweat_smile: 

---

I did want to get this into v12, but forgot about it. Probably should be considered a breaking change :man_shrugging: 

v13 release after v12.1 maybe?

**Comment by georglauterbach** [comment]
> We may want to add a minor test that greps 465  in `/etc/services` of the container to confirm it is assigned `submissions`. If the base image changes, that sometimes won't be the case (surprisingly with Fedora), so it'd be good to catch that instead of potential confusion troubleshooting it down to that issue :sweat_smile: 

👍🏼

> I did want to get this into v12, but forgot about it. Probably should be considered a breaking change :man_shrugging: 
>
> v13 release after v12.1 maybe?

I thought this was fine for v12.1.0, because I see no reason that this is a breaking change. Why would you consider this a breaking change?

**Review by casperklein — APPROVED** [review]

**Comment by polarathene** [comment]
> Why would you consider this a breaking change?

If someone depends on `smtps` being configured here?:

https://github.com/docker-mailserver/docker-mailserver/blob/adb38207ad35101bb01ce21621baa1c342fa205d/target/postfix/master.cf#L30-L31

Some issues that show this could happen:

- https://github.com/docker-mailserver/docker-mailserver/issues/2929 uses `postfix-master.cf` with `smtps/inet/smtpd_upstream_proxy_protocol = haproxy`
- https://github.com/docker-mailserver/docker-mailserver/issues/2601#issuecomment-1135520225 (_not directly, but semi-related advice_)
- Fail2Ban upstream config [regex may only recognize `smtps`, not `submissions`](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/postfix.conf#L13) (_I haven't looked into how relevant that is, just another example of where behaviour may change unexpectedly_)

Since we provide ways to target configuration for `smtps`/`submissions`, and it's used as the syslog name for monitoring logs, I wouldn't be surprised if some users find it a breaking change. @wernerfred usually views this sort of change as breaking as well.

---

For reference, a comment motivating this `smtps => submissions` change (_since none was provided in the PR description_): https://github.com/docker-mailserver/docker-mailserver/issues/3170#issuecomment-1465395403

**Comment by casperklein** [comment]
> Some issues that show this could happen:

Good points. If there isn't a huge benefit, but possible (future) problems with stuff like fail2ban expecting smtps, I think it's not worth and we shouldn't change it.

**Comment by polarathene** [comment]
> I think it's not worth and we shouldn't change it.

It's fine for introducing as a breaking change. Users can raise actual bug reports to surface the problems.

Like I said, I am not sure if fail2ban monitoring `smtps` was relevant, just an example that came to mind. I looked through `git blame` and realized that the regex still covers `submissions`, even though it was added back in 2016. So no issue there with this change.

Users may still have their own config / scripts or other tools that are more explicitly expecting `smtps`, which is my main point of respecting semver by only applying the change for a major release.

**Comment by georglauterbach** [comment]
I had a glance at our F2B config as well, and it is using `submissions`, not `smtps`, as @polarathene said.

I am fine with waiting for the next major with this. It will probably not even take too long for v13.0.0 to come out, due to other changes I have in mind.

**Comment by georglauterbach** [comment]
**INFO**: Marked this with `meta/feature-freeze` now to indicate this PR is not to be merged before v12.1.0 is released.

**Pull request merged**
