### PR TITLE
tests(feat): Complete rewrite of letsencrypt tests

### PR DESCRIPTION
**Pull request by polarathene**
# Description

This has been extracted from https://github.com/docker-mailserver/docker-mailserver/pull/2245 as it does not need to be part of that PR.

~~It is rather dependent upon other PRs split out ( #2274 #2275 #2278 #2279 #2284 ) from the referenced PR #2245 above being merged to successfully pass the test suite.~~ (_**EDIT:** All merged_)

---

**Summary:** This test still has the same coverage, with some additional tests covered and corrected/improved.

- **Adopted the `common_container` helper functions from `test_helper/common`:**
   _This minimizes the initial setup and cleanup at the end of tests, highlighting only what's relevant._
- **Much of the test logic has been extracted into re-usable functions rather than hard-coded:**
   _Many of which can be used for the other TLS tests at a later stage._
- **Heavy inline documentation:**
   _Along with some TODO items that still need to be addressed. Should be easier to grok the test flow._
- **The older `test/config/letsencrypt` certs have been removed from the project:**
   _Replaced in the test with `example.test` certs, which aren't expired and are better tested against._

---

**For ease of review via diffs**, I have carefully staged out additional commits to show an iterative process of refactoring the original test into better shape before it adopts the `common_container` approach, and then converts to `example.test` certs, followed by adding additional test coverage to finish up.

See individual commits for further details on changes they introduced if needing more information.

## Type of change

- [x] New feature (non-breaking change which adds functionality) (_for TLS tests at least_)
- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by polarathene** [comment]
This PR was made prior to a related one being merged which [added a minor fix for this test to pass wildcard `example.com`](https://github.com/polarathene/docker-mailserver/commit/e9a3f092191618c2a1bdaba1ccd32f25247934b6#diff-2f12468060edb753ca5cb75902ed0b6b19b7174d1f30e2add8d5501d6506ac32), to keep resolving the conflict simple, the change was reverted back to `mail.my-domain.com` to remain consistent with the value across commits (which is later replaced for the `example.test` certs.

That's the only change early on that required a force push :sweat_smile:

**Review by georglauterbach — APPROVED** [review]
Really nice work!

**Comment by polarathene** [comment]
I know everyone is quite busy, no rush but one more review is needed so pinging maintainers for anyone that finds the time to spare.

**Review by wernerfred — APPROVED** [review]
LGTM (from an overall perspective - could be that there are some minors but they can be adressed later) and as far as test are passing should be fine too.

Thanks @polarathene for putting this together and adding comments like a pro. Future contributors will Thank you, i'm Sure.

**Comment by polarathene** [comment]
Cheers to you both for taking a look over! :grinning: 

@casperklein did you want to review this as well, or am I good to merge? :)

**Comment by casperklein** [comment]
Thx for asking. But I'll definitely have no time in the next two weeks for a review. Feel free to merge 👍

**Comment by georglauterbach** [comment]
Merged it myself because I have another upcoming PR that I did not want to rebase :D I figured this was okay :)

**Comment by polarathene** [comment]
> But I'll definitely have no time in the next two weeks for a review.

Does that also apply to to the remaining `check-for-changes.sh` PR you wanted to review? Or are you ok if another maintainer reviews and approves for merge before then?

> Merged it myself because I have another upcoming PR that I did not want to rebase :D I figured this was okay :)

I assume that was not the housekeeping one you opened, since that would make no sense :confused: 

Besides the test file itself, there wasn't really much changes elsewhere in this PR that it should require rebasing? (_not that I could see that being a problem before pushing a PR if needed_)

I generally prefer merging these larger PRs of mine since I tend to avoid a merge commit message with all of the PR commit messages concatenated by slimming it down to only the main highlights that are relevant; often from a part of my opening PR message like the summary. Too late now as that would now require rewrite of history on master :(

Ah well, no worries :sweat_smile:

**Comment by georglauterbach** [comment]
I will leave merging your commits to yourself in the future, sorry.

**Comment by polarathene** [comment]
@georglauterbach don't worry about it, all good :)

I was just a little confused what the rush was regarding avoiding a rebase (_I thought that is what all the merge commits from master to each PR was removing the need for?_).

**Comment by georglauterbach** [comment]
> I thought that is what all the merge commits from master to each PR was removing the need for?

Indeed, but I prefer rebasing over merging in some occurrences. Not that it mattered too much here :)

**Comment by casperklein** [comment]
> Does that also apply to to the remaining check-for-changes.sh PR you wanted to review?

No.

> Or are you ok if another maintainer reviews and approves for merge before then?

The more reviews, the better 👍 But I doubt, you'll find one 😉 After three weeks some would probably already did a review.

**Pull request merged**
