### PR TITLE
ci: update to new output format on GH actions

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

See <https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/>

## Type of change

- [x] Update to component due to deprecation notice

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by casperklein — APPROVED** [review]

**Comment by casperklein** [comment]
>-  I have commented my code, particularly in hard-to-understand areas
>-  I have made corresponding changes to the documentation (README.md or the documentation under docs/)
>-  If necessary I have added tests that prove my fix is effective or that my feature works

Are you sure? 😄

**Comment by georglauterbach** [comment]
> > * I have commented my code, particularly in hard-to-understand areas
> > * I have made corresponding changes to the documentation (README.md or the documentation under docs/)
> > * If necessary I have added tests that prove my fix is effective or that my feature works
> 
> Are you sure? smile

Not sure I follow, haha :D What did I miss?:)

**Comment by casperklein** [comment]
> I have made corresponding changes to the documentation

You did not make changes to the docs for example ;-)

**Comment by georglauterbach** [comment]
> > I have made corresponding changes to the documentation
>
> You did not make changes to the docs for example ;-)

I always read this like "if there changes to the docs necessary, I did them" 🙈 I can adjust the description though 🙃

**Review by polarathene — APPROVED** [review]

**Pull request merged**
