### PR TITLE
Improve VIRUSMAILS_DELETE_DELAY usage

### PR DESCRIPTION
**Pull request by casperklein**
# Description

The `VIRUSMAILS_DELETE_DELAY` variable is set in multiple places. With the introduction of `/etc/dms-settings`, this can be simplified. 

Discussed/Discovered partly here: https://github.com/docker-mailserver/docker-mailserver/pull/2264#issuecomment-955603197#

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
Does anyone knows, why shellcheck doesn't care about sourcing here:

https://github.com/docker-mailserver/docker-mailserver/blob/c7dec1e33086bbaf8609b0db6bc8799da5d5bb5b/target/bin/listmailuser#L7

but complaining [here](https://github.com/docker-mailserver/docker-mailserver/runs/4068102148?check_suite_focus=true)?

**Comment by georglauterbach** [comment]
> Does anyone knows, why shellcheck doesn't care about sourcing here:
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/c7dec1e33086bbaf8609b0db6bc8799da5d5bb5b/target/bin/listmailuser#L7
> 
> but complaining [here](https://github.com/docker-mailserver/docker-mailserver/runs/4068102148?check_suite_focus=true)?

A very good question, I have no idea :D

**Review by georglauterbach — APPROVED** [review]

**Review by polarathene — APPROVED** [review]

**Comment by polarathene** [comment]
> Does anyone knows, why shellcheck doesn't care about sourcing here:

It seems this was missed during review:

https://github.com/docker-mailserver/docker-mailserver/blob/c7dec1e33086bbaf8609b0db6bc8799da5d5bb5b/test/linting/lint.sh#L121

`--source-path="${SCRIPT_DIR}"` is probably what was intended as that's defined earlier in the script. No reference of `SCRIPTDIR` anywhere.

What I do find odd though is why the errors are reduced with that, but substituting the value with say `x` instead did not have the same effect but should be just as invalid :confused: 

---

**EDIT:** Nope, nevermind [`SCRIPTDIR` is a special value for `shellcheck`](https://github.com/koalaman/shellcheck/wiki/Directive#source-path). Without that you will get the failure for `listmailuser` as well among others such as the last var in `start-mailserver.sh` VARS list/section.

Which might hint that it's a similar behaviour with `. /etc/dms-settings`, it only reports the last occurrence for whatever reason.. In [my `common.bash` PR](https://github.com/docker-mailserver/docker-mailserver/pull/2275), you'll see that the bounced spam test update adds a shellcheck disable comment only to the 2nd test case, without needing to do it for the first one despite no difference apart from declaration/source order in the file.

**Comment by casperklein** [comment]
>  among others such as the last var in start-mailserver.sh VARS list/section.

I was wondering about this also some time ago 😆

**Pull request merged**
