### PR TITLE
update: make the Dovecot community repository the default

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

This PR makes the Dovecot community repository the default, as it contains the latest version of Dovecot.

Not sure whether this can go into v11.3 or if it has to go into v12.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by polarathene — APPROVED** [review]

**Comment by wernerfred** [comment]
> Not sure whether this can go into v11.3 or if it has to go into v12.

`v12` i would say as default behaviour changes without interaction

**Comment by casperklein** [comment]
For the record:

Dovecot Community Version: 2.3.19
Dovecot Debian Version: 2.3.13

At the moment, there should only minor changes/fixes between those versions (but I haven't verified that).

On the other hand, there is no immediate need for this now, so postponing this to v12 should be fine?

**Comment by georglauterbach** [comment]
Marked it for v12. v11.3 release phase should begin soon.

**Comment by georglauterbach** [comment]
currently waiting for #2937

**Comment by georglauterbach** [comment]
We can now merge PRs that go into v12, so this should be good to go I guess :) @casperklein

**Comment by casperklein** [comment]
@georglauterbach We could just set `ARG DOVECOT_COMMUNITY_REPO=1`. So in case there are any issues for someone, switching back is easy. The final code removal could be done in a later release.

**Comment by georglauterbach** [comment]
> @georglauterbach We could just set `ARG DOVECOT_COMMUNITY_REPO=1`. So in case there are any issues for someone, switching back is easy. The final code removal could be done in a later release.

Okay, I will adjust the PR.

**Review by casperklein — APPROVED** [review]

**Comment by georglauterbach** [comment]
ping @polarathene :)

**Review by polarathene — APPROVED** [review]

**Pull request merged**
