### PR TITLE
setup.sh improved

### PR DESCRIPTION
**Pull request by casperklein**
# Description

- EXIT trap removed
- `_unset_vars` function removed
-  ~~`_get_current_directory` function replaced with simpler approach~~
- variable list ordered
- renamed `USING_SELINUX` to `USE_SELINUX` like the rest of the `USE_` stuff.

Partly discussed here: #1885

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the documentation)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by wernerfred — COMMENTED** [review]
So as you removed a function we can safely decrease the image version number 🃏 🤣

**Comment by casperklein** [comment]
Absolutely 😆

**Comment by casperklein** [comment]
Probably we cannot get rid of `_get_current_directory`, because we need an absolute path for `docker -v` command.

**Comment by aendeavor** [comment]
> Probably we cannot get rid of `_get_current_directory`, because we need an absolute path for `docker -v` command.

🤣 so there it was, the need for an absolute path, hiding in plain side.

**Review by aendeavor — APPROVED** [review]

**Review by wernerfred — APPROVED** [review]

**Pull request merged**
