### PR TITLE
docs(podman): Fix broken links and add version hints

### PR DESCRIPTION
**Pull request by p-fruck**
# Description

This is a follow up of #2393, where I accidentally added broken links to the podman documentation.

In addition to this fix, I've added some version hints to the changes introduced in the aforementioned PR to circumvent issues like [this](https://github.com/docker-mailserver/docker-mailserver/issues/2411#issuecomment-1043542552)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by wernerfred — COMMENTED** [review]
The Version warning should afaik not be necessary as the docs are Versioned as well and released Always together with a new Container Version. 
Looking at the "Edge" Docs is valid for the "Edge" build of the Container. But switching to Docs Version "10.4" (which counts for the 10.4 builds) will not contain the newest additions. 

In fact we implemented the Versioned Docs for exactly that reason, to avoid updating references and Versions throughout the Docs. 

If it Happens to be the Case that "newer" Docs are in a "older" Release we messed Up the Release/merge process but not the Docs (content)

**Comment by p-fruck** [comment]
Hmm, seems like I should enable JS every once in a while... Now I see the versioning dropdown :smile: I'll revert the versioning related changes from the docs. Should I also revert [this line](https://github.com/p-fruck/docker-mailserver/blob/e22b3205f26663366e0ace35ae3a598536508abf/mailserver.env#L52) in the env file?

**Review by polarathene — APPROVED** [review]

**Comment by georglauterbach** [comment]
> Should I also revert the change in [this line](https://github.com/p-fruck/docker-mailserver/blob/e22b3205f26663366e0ace35ae3a598536508abf/mailserver.env#L52) in the env file?

Yes. The `none` case is not be visible for the current docs and will only appear from `10.5.0` if I'm not mistaken.

**Comment by p-fruck** [comment]
Alright, I've reverted all changes except for the typo and the broken links :+1:

**Review by polarathene — APPROVED** [review]

**Review by wernerfred — APPROVED** [review]
Thanks

**Pull request merged**
