### PR TITLE
docs(deps): update mkdocs-material to v7.1.2

### PR DESCRIPTION
**Pull request by wernerfred**
# Description

update mkdocs-material to v7.1.2

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the documentation)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by aendeavor — APPROVED** [review]

**Comment by williamdes** [comment]
@aendeavor why the last release is a pre-release ?

**Comment by aendeavor** [comment]
> @aendeavor why the last release is a pre-release ?

Wanted to wait for the other, current PRs to be merged before releasing it properly:)

**Comment by wernerfred** [comment]
I think we should always use pre-releases immediately after a realse as preparation for the next one. We all can edit it and as soon as one of us merges a PR he can add the changes to the pre-release. Then if the next release is in the pipe one could simply relase the pre release bc it is already prepared with all the changes that happened in the mean time.
Pre-Releases are only visible to org members i think?!

**Comment by williamdes** [comment]
> I think we should/could always use pre-releases immediately after a realse as preparation for the next one. We all can edit it and as soon as one of us merges a PR he can add the changes to the pre-release. Then if the next release is in the pipe one could simply relase the pre release bc it is already prepared with all the changes that happened in the mean time.
Pre-Releases are only visible to org members i think?!

Oh no, pre-releases are visible to anyone

What disturbs me is that the tag is a release tag and not a pre-release tag.
https://github.com/docker-mailserver/docker-mailserver/tree/v9.2.0

Should be `9.2.0-pre` or something semver compatible.

> I think that is also the reason why everyone got a notification as a new tag was published

Not when a tag is pushed but when a GH release is published


> Wanted to wait for the other, current PRs to be merged before releasing it properly:)

Changing tags is bad (IMO), it should be definitive



Let me know all your thoughts

**Comment by aendeavor** [comment]
> EDIT: @aendeavor i think you made a little mistake by specifiing a tag. Now the release will not include newer changes as the tag is fixed on f7836c8

Yes, I realized this too. I didn't know one could omit the tag. How do we go about the release of `10.0.0`: I can remove the `9.2.0` image from Docker Hub and we can remove the tag from GitHub as well. This will still impact the image version `docker-mailserver:9`. What do we do? One could build the image locally again, tag it as `9` and push it to Docker Hub.

**Comment by aendeavor** [comment]
> What disturbs me is that the tag is a release tag and not a pre-release tag.
> https://github.com/docker-mailserver/docker-mailserver/tree/v9.2.0
> 
> Should be `9.2.0-pre` or something semver compatible.

Yes, this would have been better. As I said, I didn't know GitHub builds pre-release tags...

> > I think that is also the reason why everyone got a notification as a new tag was published
>
> Not when a tag is pushed but when a GH release is published

Yes

> > Wanted to wait for the other, current PRs to be merged before releasing it properly:)
> 
> Changing tags is bad (IMO), it should be definitive

True as well - I didn't know you could just leave out the tag

**Comment by aendeavor** [comment]
I will revert the 9.2.0 release and push the correct images over `latest` and `9`

**Comment by aendeavor** [comment]
Ah, now I know what I did wrong: I wanted to save this as a draft, not publish it...

**Comment by wernerfred** [comment]
> Ah, now I know what I did wrong: I wanted to save this as a draft, not publish it...

And the drafts are only visible to us. That's what i meant ;)

**Comment by wernerfred** [comment]
> EDIT: I have now re-triggered the job for `9.1.0`, which should push the "old" images correctly.

Where? Currently `edge` is build using `8313d9753bc7f368078464a9a33fc5e766cc29d2`

**Comment by aendeavor** [comment]
> > EDIT: I have now re-triggered the job for `9.1.0`, which should push the "old" images correctly.
> 
> 
> 
> Where? Currently `edge` is build using `8313d9753bc7f368078464a9a33fc5e766cc29d2` 

If you check Docker Hub, about 20 minutes ago the tags for `9`, `9.1`, `9.1.0` and latest were updated. `edge` has nothing to do with this release.

**Comment by williamdes** [comment]
Nice!
I always review diffs between releases for audit purposes
Good job on the mailcrypt docs, this will help me a lot
That said it is sill not clear who can read the keys
If an attacker accesses the storage, the keys will also be there

Anyway, about releases I propose that we open a github discussion just before releases so subscribers could prepare or audit versions?

By the way are tags signed by a member gpg key?
All all members using gpg keys to sign their tags and commits?

**Comment by aendeavor** [comment]
> Anyway, about releases I propose that we open a github discussion just before releases so subscribers could prepare or audit versions?

I thought about this too. We can couple this with @wernerfred's idea - which I already tried but pressed the wrong button - opening a draft for next release early.
 
> By the way are tags signed by a member gpg key? All all members using gpg keys to sign their tags and commits? 

I'm not sure, but it would be logical to assume that a tag refers to a commit which can be signed. AFAIK all regular maintainers sign their commits, which would imply that tags are signed too.

**Comment by williamdes** [comment]
> I'm not sure, but it would be logical to assume that a tag refers to a commit which can be signed. AFAIK all regular maintainers sign their commits, which would imply that tags are signed too.

Well from what I see most of people do not sign their commits, and sign their tags
Anyway that would be nice that everyone checks that signing is active for everyone
And then also be sure members have 2FA enabled

That would add layers of security on a repository that could lead to a big data breach

One more topic: we could probably ask for an official Docker image, I already did that with some help from `@J0WI` at phpMyAdmin.

Well, maybe it is best that we open a discussion and continue about security

And maybe `@emanuelb` would have some security advice for us

I am pretty sure we can agree that if an unwanted change gets in this image servers in the world would be compromised with all their users privacy

**Comment by aendeavor** [comment]
Although I'm always for a discussion about security, I think there is no immediate danger inbound.

@wernerfred is reworking the CI workflow to only allow reviewed PRs to be merged. The configuration is AFAIK well reviewed.

But if you want, tag us in a discussion.

**Pull request merged**
