### PR TITLE
ARM build fix

### PR DESCRIPTION
**Pull request by casperklein**
# Description

Possible arm build fix

Fixes #1965

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aendeavor** [comment]
The error shown by `docker buildx` is very cryptic indeed... I'd just restart the test.

**Comment by aendeavor** [comment]
And why did the latest pipeline on `master` succeed? 🤣

**Comment by casperklein** [comment]
See my https://github.com/docker-mailserver/docker-mailserver/pull/1965#issuecomment-841707214

**Comment by aendeavor** [comment]
Wait. I may miss something here, but couldn't we:

1. Turn on the `--insecure` setting for `curl`, as this _could_/_should_ be the reason for CI to fail
2. Revert #1970 to just test against `amd64`
3. With a bit of luck, habe CI fixed and a lot less work :D

Did I miss something?

**Comment by casperklein** [comment]
Yes, also possible. But I'll start now on adding buildx. Let's see how this goes 😄

**Comment by casperklein** [comment]
Another CI adjustment is needed. I am just testing it. If it's fine, i'll provide a hopefully final PR.

**Comment by casperklein** [comment]
The CI will be fine with #1974 👍

**Review by wernerfred — APPROVED** [review]

**Comment by wernerfred** [comment]
oh i approved the changes but the workflow wasn't finished. Auto-merge went through tho so we need to keep an eye on the running CI

**Comment by casperklein** [comment]
Tests are also fine 🎉

**Comment by polarathene** [comment]
> oh i approved the changes but the workflow wasn't finished. Auto-merge went through tho so we need to keep an eye on the running CI

When I contributed to Gatsby they had a auto-merge on green (all tests pass), not sure if that's supported by default on Github for maintainers or was via some third-party integration they added.

Additionally with Github Actions, that may not always be reliable as some CI jobs can be related but triggered after the initial checks/actions complete. I've seen the UI only show 1 listing in the check suite as a result and treat it as "green" but then the 2nd workflow which manually manages it's status causing the UI to update with a 2nd check item. Having some delay timer might work around that concern.

**Comment by wernerfred** [comment]
The problem is that we can define which workflows need to pass at least before a merge is possible. We have chosen the "linting" one here as this one runs every time. We could also add the "test_pr" but then this one also needs to run even if we only add a typo fix on readme for example.
I will double check if there are new settings available, otherwise we be especially cautious about the "enable auto-merge" feature if there is a test running currently (or to approve only if the test passes).

**Pull request merged**
