### PR TITLE
Dockerfile: use heredocs

### PR DESCRIPTION
**Pull request by casperklein**
# Description

Since version `1.3-lab` of Dockerfile, heredoc syntax is available.

This PR converts the countless `&& \` lines into better readable heredocs.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by georglauterbach — APPROVED** [review]
LGTM 👍

**Comment by polarathene** [comment]
Not usually a fan of heredocs myself, but this is a pretty decent use-case for it! :sweat_smile:

**Comment by polarathene** [comment]
This took a little while to track down. I wanted to know about the `1.3-labs` requirement as `-labs` is experimental/beta testing channel, not the stable BuildKit releases AFAIK, which I would not be in support of merging as a further restriction on build environments.

Thankfully, this was [promoted to a stable in the `dockerfile-1.4` syntax release](https://github.com/moby/buildkit/blob/dockerfile/1.4.3/frontend/dockerfile/docs/syntax.md#here-documents). So it fits with the March 2022 requirement for other features we depend on with changes to `Dockerfile` for better build caching :+1:

**Comment by casperklein** [comment]
I should have been more clear. By writing *since* I meant that the feature was added in the next non-experimental version (1.4 - which we currently use). I totally agree, not to add any experimental things 👍

**Pull request merged**
