### PR TITLE
Add warning when container was restarted

### PR DESCRIPTION
**Pull request by casperklein**
# Description

DMS does not (yet) support container restarts and a clean start is necessary. This PR adds a warning when DMS was restarted.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

**Comment by polarathene** [comment]
Your warning logs are better, but we technically already have this logic?

https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/scripts/startup/check-stack.sh#L17-L24

**Comment by casperklein** [comment]
You are right, I forgot about this 😆

If you and Georg thinks this one is better, I can remove `_check_improper_restart()`. Otherwise we can close this PR.

**Comment by georglauterbach** [comment]
I don't mind this solution of using `if else`, I just like the wording in the current check better TBH. Technically it is also a check; having it in `check-stack.sh` seems most appropriate to me.

**Comment by polarathene** [comment]
Several scripts rely on this file marker, so it's fine and appropriate to keep the check in `check-stack.sh` 👍 

Current wording is good, but the explicit guidance of `Use 'docker compose up --force-recreate'` is also a helpful addition to communicate (_plenty of users that raise bug reports don't seem to actually check the debug docs guidance_), but it's not clear if they're seeing that restart warning and just not sure how to correctly restart/destroy the container by re-recreating it.

**Pull request closed without merging**
