### PR TITLE
Use buildx in test_merge_requests.yml

### PR DESCRIPTION
**Pull request by casperklein**
# Description

I tried to add buildx to `test_merge_requests.yml`.

Fixes bad PR #1970 
Closes #1971 (added by @aendeavor)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aendeavor** [comment]
Seems to work fine, I have no objections: LGTM 👍 

@wernerfred What's your take?

**Review by aendeavor — DISMISSED** [review]

**Review by wernerfred — DISMISSED** [review]
I think the whole cache part is not necessary as the image (layers) differ for every architecture and we are only building once (compared to default_on_push where we have a local build during test and then a local build during push).
So caching will add only time but no benefit if i didn't overlook something.

Apart from the time aspect caching does not change functionality so this can be merged directly or caching can be excluded to optimize the workflow further.

**Comment by casperklein** [comment]
I just copy/pasted it from` default_on_push.yml`. The same came to my mind also, after providing this PR. But I wasn't sure, so I leaved it unchanged.

**Comment by casperklein** [comment]
I have removed the cache stuff.

**Review by wernerfred — APPROVED** [review]

**Review by aendeavor — APPROVED** [review]

**Comment by aendeavor** [comment]
GitHub behaves strangely ATM. The check does not start(?) At least I do not see it.

**Comment by casperklein** [comment]
I noticed the same in other repos. The tests are queued. GitHub seems a bit sluggish today.

**Comment by wernerfred** [comment]
Seems Like we have to wait until ghactions are operational again: https://www.githubstatus.com/

**Pull request merged**
