### PR TITLE
Add ability to build with Dovecot community repository

### PR DESCRIPTION
**Pull request by casperklein**
# Description

This PR adds the ability, to use the latest Dovecot packages from the community repository. For this, the build argument `DOVECOT_COMMUNITY_REPO=1` must be used.

The current version for Dovecot in the debian repository is `2.3.13`. In the community repository it is `2.3.19.1`.

There shouldn't be any problems for existing setups switching to the community repository, as the version gap is only minor. However to be safe, we can wait for the next DMS major release, to make the community repository the default.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
Test 217 [failed](https://github.com/docker-mailserver/docker-mailserver/actions/runs/3123479976/jobs/5066173382#step:5:225). I've restarted the test action.

**Comment by georglauterbach** [comment]
Looks good - one question though: as with F2B, is there a special reason to not use the community repository all the time? The comfort of choosing whether to build with the Repo is very nice, I won't block merging, but it seems a bit unnecessary to me :)

**Comment by casperklein** [comment]
> There shouldn't be any problems for existing setups switching to the community repository, as the version gap is only minor. However to be safe, we can wait for the next DMS major release, to make the community repository the default.

It's just to avoid the minimal chance of issues fo existing setups. Therefore my proposal was, to make it now optional and later the default.

We could also switch right now. I am using the community repo for a long time and had never issues.

**Comment by georglauterbach** [comment]
> > There shouldn't be any problems for existing setups switching to the community repository, as the version gap is only minor. However to be safe, we can wait for the next DMS major release, to make the community repository the default.
> 
> It's just to avoid the minimal chance of issues fo existing setups. Therefore my proposal was, to make it now optional and later the default.
> 
> We could also switch right now. I am using the community repo for a long time and had never issues.

I would go with postponing merging this until after the release of v11.2.0 and then just use the community repo for all builds :) But I am completely fine with your proposal too. What do other @docker-mailserver/maintainers say?

**Comment by casperklein** [comment]
I would prefer merging this, as it has no drawbacks, but gives easily the ability to test the community version right now. Later it's pretty simple to remove the condition and make it the default.

**Comment by georglauterbach** [comment]
> I would prefer merging this, as it has no drawbacks, but gives easily the ability to test the community version right now. Later it's pretty simple to remove the condition and make it the default.

Very much fine with me :D 

One last question: this PR includes changes from the currently open F2B PR right, so we merge the F2B PR beforehand?

**Comment by casperklein** [comment]
Yeah, I've created a new branch based on the f2b branch. That's why f2b commits also show up here. f2b should be merged first.

**Comment by georglauterbach** [comment]
Same old issue with CI: only 217 tests are executed because `setup_file` for `tests.bats` did not succeed. This become very annoying..

**Comment by wernerfred** [comment]
Shouldn't the changes be added to `CHANGELOG.md` like proposed/defined by @georglauterbach in #2789? Or am i missing something?

**Comment by georglauterbach** [comment]
> Shouldn't the changes be added to `CHANGELOG.md` like proposed/defined by @georglauterbach in #2789? Or am i missing something? Or does this count only from `11.2.0` onwards?

They should (in theory), but as the new changelog format has not been merged yet, I think it's fine for the follow-up PR that enabled the community Repo by default to add a changelog notice.

**Comment by casperklein** [comment]
> Same old issue with CI: only 217 tests are executed because `setup_file` for `tests.bats` did not succeed. This become very annoying..

On the 4th attempt, the tests run successful 🎉

**Review by wernerfred — APPROVED** [review]

**Review by polarathene — APPROVED** [review]

**Review by georglauterbach — APPROVED** [review]

**Pull request merged**
