### PR TITLE
linting: use local scripts to remove sudo need

### PR DESCRIPTION
**Pull request by ap-wtioit**
# Description

this change installs the linting tools in a local tools directory. this removes the need for `sudo curl` and replacing binaries in /usr/local/bin and /usr/bin.

Issues with the previous code:
* /usr/local/bin and /usr/bin might be shared on CI systems by multiple builds influencing each other
* the old code might leave some of the tools shared with other build unexecutable when downloading them to /usr/local/bin and /usr/bin for short periods of time (breaking other builds)

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

Info @wt-io-it

### CODE REVIEW

**Comment by aendeavor** [comment]
I like this change.

LGTM

**Review by aendeavor — APPROVED** [review]

**Review by wernerfred — COMMENTED** [review]
A few thoughts from my side:

Imho there is a problem when "installing" to a local path in the repository as one might run these linting checks locally to test befor opening a PR. Therefore the local repository would include the tools as a local change. There are multiple possibilities to solve this. For example make it optional to remove them afterwards via `make clean` or to add `tools/**` to `.gitignore`.

For a long sight: I am preparing a PR (which I came up with already before the migration started) to switch the linting tools etc to their docker versions. This will solve the issue with "installing" completely and should not be a problem for anyone as everyone is using docker already when using docker-mailserver. 
But for the meantime i like your change and will approve if the issue mentioned above is resolved/discussed.

**Comment by ap-wtioit** [comment]
@wernerfred please look at the Files changed tab, tools is already added to .gitignore

**Comment by aendeavor** [comment]
There are multiple possibilities to solve this. For example make it optional to remove them afterwards via `make clean` or to add `tools/**` to `.gitignore`.

Did I miss something?

``` IGNORE
#################################################
###  Linting Tools  #############################
#################################################

tools/
```

?

**Comment by wernerfred** [comment]
omg, my bad. Looked at the changed files of course but (howsoever) must have overlooked changes to `.gitignore`

**Review by wernerfred — APPROVED** [review]

**Pull request merged**
