### PR TITLE
Work around possible problems with init

### LINKED ISSUE #763: Image cannot be built after update & upgrade
Hi,

I'm using this image as base image for our own uses. Basically we just install few additional packages and add few files into the image.

After update & upgrade, the image fails to build because of this error:

```
Setting up postfix (3.1.0-3ubuntu0.2) ...
Installing new version of config file /etc/init.d/postfix ...

Postfix configuration was untouched.  If you need to make changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Running newaliases
postalias: fatal: unsupported dictionary type: texthash. Is the postfix-texthash package installed?
dpkg: error processing package postfix (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of postfix-ldap:
 postfix-ldap depends on postfix (= 3.1.0-3ubuntu0.2); however:
  Package postfix is not configured yet.

dpkg: error processing package postfix-ldap (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
17 added, 42 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for systemd (229-4ubuntu21) ...
Errors were encountered while processing:
 postfix
 postfix-ldap
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Affected tags: 2.1, 2.3, latest

This might have something to do with pull request #382

**How to reproduce**

Build using following dockerfile

```
FROM tvial/docker-mailserver:2.3

RUN DEBIAN_FRONTEND=noninteractive apt-get update -q  && \
	apt-get -y upgrade
```

### PR DESCRIPTION
**Pull request by Craeckie**
# Description

When building it I ran into [this](https://github.com/docker-mailserver/docker-mailserver/issues/763#issuecomment-343751893). It's some problem with init not working as expected. It seems to appear only for some people in some cases.

The code from [stackoverflow](https://stackoverflow.com/a/48782486) (almost) fixes the problem. Just a `-e` was missing.

So this PR also fixes #763

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by casperklein** [comment]
Please provide some more information and how to re-produce that problem. Do you install additional packages as in the linked issue? 
There are currently no known issues about failing builds (on supported platforms).

**Comment by georglauterbach** [comment]
> Please provide some more information and how to re-produce that problem. Do you install additional packages as in the linked issue?
> There are currently no known issues about failing builds (on supported platforms).

I agree. Please elaborate :)

**Comment by Craeckie** [comment]
Sorry for the late reply, been quite busy the last few days.

Ok, after quite some time looking for the error it turns out it wasn't apt at all. The command `gpg --keyserver ${FAIL2BAN_GPG_PUBLIC_KEY_SERVER} --recv-keys ${FAIL2BAN_GPG_PUBLIC_KEY_ID}` fails, but since the output was suppressed I always assumed apt was causing it. I will further investigate when I have time for it.

What helped me a lot was activating the command output with `set -x` right at the beginning of RUN. This makes searching for the error much easier! You should really add that to the Dockerfile. Should I create a PR for this?

**Comment by georglauterbach** [comment]
> [...] The command `gpg --keyserver ${FAIL2BAN_GPG_PUBLIC_KEY_SERVER} --recv-keys ${FAIL2BAN_GPG_PUBLIC_KEY_ID}` fails, but since the output was suppressed I always assumed apt was causing it. I will further investigate when I have time for it.

How was the output suppressed? The full command reads:

``` BASH
gpg --keyserver ${FAIL2BAN_GPG_PUBLIC_KEY_SERVER} --recv-keys ${FAIL2BAN_GPG_PUBLIC_KEY_ID} 2>&1

**Comment by Craeckie** [comment]
> How was the output suppressed? The full command reads:
> 
> ```shell
> gpg --keyserver ${FAIL2BAN_GPG_PUBLIC_KEY_SERVER} --recv-keys ${FAIL2BAN_GPG_PUBLIC_KEY_ID} 2>&1
> ```
> 
> which only prints `stderr` on `stdout`, but does not remove any output AFAIK...

I was trying to build v10.0.0, where the output was suppressed:
https://github.com/docker-mailserver/docker-mailserver/blob/a0f4a375124b3b3402d5639a7d422501c2011b97/Dockerfile#L64-L65

**Comment by georglauterbach** [comment]
I see.

@wernerfred maybe we should release `v10.0.1` as there were enough small fixes, including the F2B GPG server. What do you think?

**Comment by wernerfred** [comment]
As far as releasing means feature freeze and testing :edge for at least 7 days I'm fine with it. 
Should i prepare the release PR like last time today?

**Comment by georglauterbach** [comment]
> As far as releasing means feature freeze and testing :edge for at least 7 days I'm fine with it.
> Should i prepare the release PR like last time today?

SGTM 👍🏼

**Comment by casperklein** [comment]
There were also changes that are not bugfixes/patches. Therefore 10.1.0 should be released.

**Comment by wernerfred** [comment]
Then we need to decide whether to wait for #2080 or not ;)

**Comment by georglauterbach** [comment]
I don’t think we need to wait. We can always release `v10.2.0` afterwards if you ask me.

**Pull request closed without merging**
