### PR TITLE
release: v14.0.0

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

This PR marks the feature freeze phase for the `v14.0.0` release.

The current `:edge` image will be tested and if no bugs get reported, `v14.0.0` will be released. During this testing period, only PRs that do not change functionality will be merged.

**If you want to support us, give the latest `:edge` image a try and report any issues you encounter back to this PR.**

Documentation updates may be merged. **Feature freeze is in place until 5 Jun 2024**.

## Type of change

- [x] Release

## Release-Checklist:

- [x] Update `CHANGELOG.md`
- [x] Draft release
- [x] Update version in `VERSION`

### CODE REVIEW

**Comment by polarathene** [comment]
> **Feature freeze is in place until ~ 1 Jun 2024**.

> The current `:edge` image will be tested for roughly **5 days** and if no bugs get reported, `v14.0.0` will be released.

Bit of a mismatch there?

If https://github.com/docker-mailserver/docker-mailserver/issues/4011#issuecomment-2105904974 is a blocker I am not sure if I'll have time within 5 days to tackle it. If release is planned for June 1st then I can take care of it and try get in a docs update I was working on earlier this year for rewriting the accounts management page.

**Comment by georglauterbach** [comment]
Sorry for the mismatch, I was still tired at the time of writing. We absolutely have no rush, we can adjust the date freely at this time. Take whatever time you need.

**Comment by polarathene** [comment]
> Take whatever time you need.

Cheers! I don't want to block on release, let's aim for getting a release out by 1st June or earlier if possible. It's a big update with some good improvements/fixes.

I'll try find some time to get that docs page update in by then as I'd like to have that in a release of the docs before the LDAP docs are revised (_which is blocking the related open LDAP PRs_).

**Comment by georglauterbach** [comment]
Okay, then we will target 1 Jun 2024 🚀

**Comment by MohammedNoureldin** [comment]
Great, thank you guys! If you need support I am glad to help.

I will be anyway testing extensively, of course.

**Comment by polarathene** [comment]
> Maybe we can release it even earlier if the whole tests are fine.

If I can get my docs update done before then and any remaining concerns have been tackled, yes we could publish a release earlier.

Main reason to want to block on the docs update is to make it easier for users to navigate changes between v14 and v15 (_where I'd like to get LDAP changes in and relocate other docs pages_). If I can't find the time however, I won't keep blocking on it 😅

**Comment by georglauterbach** [comment]
Last commit was just a rebase.

**Comment by georglauterbach** [comment]
Last blockers for this release:

- #4033
- #4034
- #4035

**Comment by georglauterbach** [comment]
@casperklein do you have an ETA for the Fail2Ban update PR? I would consider this PR as a blocker for v14 too, unless it is too far into the future.

**Comment by georglauterbach** [comment]
@casperklein all initial blockers for this release are resolved. Shall we still wait for your Fail2Ban PR?

**Comment by MohammedNoureldin** [comment]
I am not sure what this Fail2Ban PR is about, but if it is not going to be a breaking change, and is going to take sometime, I think it is fine to schedule it for 14.1.0. Or 14.0.1 if it is a hot fix for the 14 version.

**Comment by georglauterbach** [comment]
You

> I am not sure what this Fail2Ban PR is about, but if it is not going to be a breaking change, and is going to take sometime, I think it is fine to schedule it for 14.1.0. Or 14.0.1 if it is a hot fix for the 14 version.

The F2B PR is a change that @casperklein proposed, which is about updating Fail2Ban.

You're right, though, this can go into v14.1.0 without harm. I will now rebase this PR and make it a proper PR.

**Comment by casperklein** [comment]
> @casperklein do you have an ETA for the Fail2Ban update PR? I would consider this PR as a blocker for v14 too, unless it is too far into the future.

I am on vacation right now and can't provide a PR. You wrote in the other thread, that you are going to provide one?
For me, it's not a blocker for v14. Just because the new version fixes some issue with postfix log parsing, I thought it would be a good idea to have it in the major update. We can postpone the f2b update to 14.1.0 👍

**Comment by georglauterbach** [comment]
> I am on vacation right now and can't provide a PR. You wrote in the other thread, that you are going to provide one? Edit: you updated your [comment](https://github.com/docker-mailserver/docker-mailserver/pull/4034#issuecomment-2131688488). I was confused, because I got the original response by mail.

I'm sorry for that; I quickly reverted because I became confused too :D

> For me, it's not a blocker for v14. Just because the new version fixes some issue with postfix log parsing, I thought it would be a good idea to have it in the major update. We can postpone the f2b update to 14.1.0 👍

This it will go into v14.1.0 and we can proceed as planned.

**Review by casperklein — APPROVED** [review]

**Comment by georglauterbach** [comment]
I will merge this later today and publish the release.

**Pull request merged**
