### PR TITLE
tests(rspamd): Update GTube patterns

### PR DESCRIPTION
**Pull request by georglauterbach**
# Description

Updated links and the setting's name for GTube enablement.

Integrated the [Rspamd GTube pattern](https://rspamd.com/doc/other/gtube_patterns.html) for doing nothing.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary, I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

**Comment by georglauterbach** [comment]
Will check the test failure ASAP, should be easy to resolve.

**Comment by polarathene** [comment]
For context there was a PR pushed for merging that required bumping the milestone to v15, I've got to go back through existing issues and merged PRs that were marked for v14.1 and update to reflect v15 as their associated release. I only just got a working desktop system again today 😅

**Comment by georglauterbach** [comment]
> Context for v14.1 => v15.0 milestone change:
> 
> A PR was pushed for merging that required bumping the milestone to v15. I've got to go back through existing issues and merged PRs that were marked for v14.1 and update to reflect v15 as their associated release. I only just got a working desktop system again today 😅

Shall I assist you in converting the issues/PRs from 14.1.0 to 15.0.0?

**Comment by polarathene** [comment]
> Shall I assist you in converting the issues/PRs from 14.1.0 to 15.0.0?

Oh, I would love that! 😁 

Otherwise I'll probably tackle it after I complete my review on the Podman docs PR 👍

**Comment by georglauterbach** [comment]
> > Shall I assist you in converting the issues/PRs from 14.1.0 to 15.0.0?
> 
> Oh, I would love that! 😁
> 
> Otherwise I'll probably tackle it after I complete my review on the Podman docs PR 👍

Done - I moved all items either to v15 or removed their milestone, depending on what better suites the item.

**Comment by georglauterbach** [comment]
@casperklein you can go ahead and merge this when there are no concerns left from your side :)

**Review by casperklein — APPROVED** [review]

**Pull request merged**
